/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         key: "key"
 *     }
 */
export interface TemplatesGetRequest {
    /**
     * The key of the template
     */
    key: string;
}
