// This file was auto-generated by Fern from our API Definition.

export interface TranscriptsCreateRequestKeytermsTermsItem {
    /** The word to be recognized, defined in its expected written form. */
    term: string;
}
