// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { Section } from "../../../types/Section.js";

export const Response: core.serialization.Schema<serializers.newSections.list.Response.Raw, Corti.Section[]> =
    core.serialization.list(Section);

export declare namespace Response {
    export type Raw = Section.Raw[];
}
