// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { AuthTokenRequestAuthorizationCode } from "../../../types/AuthTokenRequestAuthorizationCode.js";
import { AuthTokenRequestAuthorizationPkce } from "../../../types/AuthTokenRequestAuthorizationPkce.js";
import { AuthTokenRequestClientCredentials } from "../../../types/AuthTokenRequestClientCredentials.js";
import { AuthTokenRequestRefresh } from "../../../types/AuthTokenRequestRefresh.js";
import { AuthTokenRequestRopc } from "../../../types/AuthTokenRequestRopc.js";

export const AuthTokenRequestBody: core.serialization.Schema<
    serializers.AuthTokenRequestBody.Raw,
    Corti.AuthTokenRequestBody
> = core.serialization.undiscriminatedUnion([
    AuthTokenRequestClientCredentials,
    AuthTokenRequestAuthorizationCode,
    AuthTokenRequestAuthorizationPkce,
    AuthTokenRequestRopc,
    AuthTokenRequestRefresh,
]);

export declare namespace AuthTokenRequestBody {
    export type Raw =
        | AuthTokenRequestClientCredentials.Raw
        | AuthTokenRequestAuthorizationCode.Raw
        | AuthTokenRequestAuthorizationPkce.Raw
        | AuthTokenRequestRopc.Raw
        | AuthTokenRequestRefresh.Raw;
}
