// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface AgenticContextsGetRequest {
    /** Cap the number of history messages returned per task. */
    historyLength?: number;
}
