// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";

export const AgenticAgentsJsonRpcRequestId: core.serialization.Schema<
    serializers.agentic.AgenticAgentsJsonRpcRequestId.Raw,
    Corti.agentic.AgenticAgentsJsonRpcRequestId
> = core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.number()]);

export declare namespace AgenticAgentsJsonRpcRequestId {
    export type Raw = string | number;
}
