// This file was auto-generated by Fern from our API Definition.

import * as Corti from "../../../../src/api/index";
import { CortiClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";
import { mockOAuth } from "../../mockAuth";

describe("A2AClient", () => {
    test("jsonRpc (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            jsonrpc: "2.0",
            id: "1",
            method: "SendMessage",
            params: {
                message: {
                    role: "ROLE_USER",
                    messageId: "msg.0192f4c8-5f8d-7e61-924d-6fb09b5ead73",
                    parts: [{ text: "Code this encounter." }],
                },
            },
        };
        const rawResponseBody = {
            jsonrpc: "2.0",
            id: "msg-001",
            result: {
                task: {
                    id: "task.0192f4c8-4e7c-7d50-b13c-5eaf8a4d9c62",
                    contextId: "ctx.0192f4c8-3d6b-7c4f-a02b-4d9e7f3c8b51",
                    status: { state: "TASK_STATE_COMPLETED" },
                },
            },
            error: { code: -32600, message: "Invalid Request", data: { key: "value" } },
        };

        server
            .mockEndpoint()
            .post("/agentic/agents/agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40/a2a")
            .header("A2A-Version", "1.0")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentic.agents.a2A.jsonRpc("agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40", {
            id: "1",
            method: "SendMessage",
            params: {
                message: {
                    role: "ROLE_USER",
                    messageId: "msg.0192f4c8-5f8d-7e61-924d-6fb09b5ead73",
                    parts: [
                        {
                            text: "Code this encounter.",
                        },
                    ],
                },
            },
        });
        expect(response).toEqual({
            jsonrpc: "2.0",
            id: "msg-001",
            result: {
                task: {
                    id: "task.0192f4c8-4e7c-7d50-b13c-5eaf8a4d9c62",
                    contextId: "ctx.0192f4c8-3d6b-7c4f-a02b-4d9e7f3c8b51",
                    status: {
                        state: "TASK_STATE_COMPLETED",
                    },
                },
            },
            error: {
                code: -32600,
                message: "Invalid Request",
                data: {
                    key: "value",
                },
            },
        });
    });

    test("jsonRpc (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { jsonrpc: "2.0", id: "id", method: "SendMessage" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agentic/agents/agentId/a2a")
            .header("A2A-Version", "1.0")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.agents.a2A.jsonRpc("agentId", {
                id: "id",
                method: "SendMessage",
            });
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("jsonRpc (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { jsonrpc: "2.0", id: "id", method: "SendMessage" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agentic/agents/agentId/a2a")
            .header("A2A-Version", "1.0")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.agents.a2A.jsonRpc("agentId", {
                id: "id",
                method: "SendMessage",
            });
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("sendMessage (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            message: {
                messageId: "msg.0192f4c8-5f8d-7e61-924d-6fb09b5ead73",
                role: "ROLE_USER",
                parts: [{ text: "What is the ICD-10 code for asthma?" }],
            },
        };
        const rawResponseBody = {
            task: {
                id: "task.0192f4c8-4e7c-7d50-b13c-5eaf8a4d9c62",
                contextId: "ctx.0192f4c8-3d6b-7c4f-a02b-4d9e7f3c8b51",
                status: {
                    state: "TASK_STATE_COMPLETED",
                    timestamp: "2026-05-19T12:00:01Z",
                    message: {
                        messageId: "msg.0192f4c8-5f8d-7e61-924d-6fb09b5ead73",
                        contextId: "ctx.0192f4c8-3d6b-7c4f-a02b-4d9e7f3c8b51",
                        taskId: "task.0192f4c8-4e7c-7d50-b13c-5eaf8a4d9c62",
                        role: "ROLE_AGENT",
                        parts: [{ text: "J45.909" }],
                    },
                },
                artifacts: [{ artifactId: "art.0192f4c8-6a9e-7f72-a35e-70c1ac6fbe84", parts: [{ text: "J45.909" }] }],
                metadata: {
                    $usage: {
                        model: "corti-default",
                        inputTokens: 100,
                        outputTokens: 20,
                        cachedInputTokens: 64,
                        cacheCreationInputTokens: 0,
                        totalTokens: 120,
                        credits: 1.2,
                    },
                },
            },
        };

        server
            .mockEndpoint()
            .post("/agentic/agents/agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40/a2a/message:send")
            .header("A2A-Version", "1.0")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentic.agents.a2A.sendMessage("agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40", {
            message: {
                messageId: "msg.0192f4c8-5f8d-7e61-924d-6fb09b5ead73",
                role: "ROLE_USER",
                parts: [
                    {
                        text: "What is the ICD-10 code for asthma?",
                    },
                ],
            },
        });
        expect(response).toEqual({
            task: {
                id: "task.0192f4c8-4e7c-7d50-b13c-5eaf8a4d9c62",
                contextId: "ctx.0192f4c8-3d6b-7c4f-a02b-4d9e7f3c8b51",
                status: {
                    state: "TASK_STATE_COMPLETED",
                    timestamp: "2026-05-19T12:00:01Z",
                    message: {
                        messageId: "msg.0192f4c8-5f8d-7e61-924d-6fb09b5ead73",
                        contextId: "ctx.0192f4c8-3d6b-7c4f-a02b-4d9e7f3c8b51",
                        taskId: "task.0192f4c8-4e7c-7d50-b13c-5eaf8a4d9c62",
                        role: "ROLE_AGENT",
                        parts: [
                            {
                                text: "J45.909",
                            },
                        ],
                    },
                },
                artifacts: [
                    {
                        artifactId: "art.0192f4c8-6a9e-7f72-a35e-70c1ac6fbe84",
                        parts: [
                            {
                                text: "J45.909",
                            },
                        ],
                    },
                ],
                metadata: {
                    $usage: {
                        model: "corti-default",
                        inputTokens: 100,
                        outputTokens: 20,
                        cachedInputTokens: 64,
                        cacheCreationInputTokens: 0,
                        totalTokens: 120,
                        credits: 1.2,
                    },
                },
            },
        });
    });

    test("sendMessage (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { message: { role: "ROLE_USER", parts: [{}, {}] } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agentic/agents/agentId/a2a/message:send")
            .header("A2A-Version", "1.0")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.agents.a2A.sendMessage("agentId", {
                message: {
                    role: "ROLE_USER",
                    parts: [{}, {}],
                },
            });
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("sendMessage (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { message: { role: "ROLE_USER", parts: [{}, {}] } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agentic/agents/agentId/a2a/message:send")
            .header("A2A-Version", "1.0")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.agents.a2A.sendMessage("agentId", {
                message: {
                    role: "ROLE_USER",
                    parts: [{}, {}],
                },
            });
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("sendMessage (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { message: { role: "ROLE_USER", parts: [{}, {}] } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agentic/agents/agentId/a2a/message:send")
            .header("A2A-Version", "1.0")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.agents.a2A.sendMessage("agentId", {
                message: {
                    role: "ROLE_USER",
                    parts: [{}, {}],
                },
            });
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("streamMessage (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            message: {
                messageId: "msg.0192f4c8-5f8d-7e61-924d-6fb09b5ead73",
                role: "ROLE_USER",
                parts: [{ text: "What is the ICD-10 code for asthma?" }],
            },
        };
        const rawResponseBody =
            'event: \ndata: {"data":"{\\"task\\":{\\"id\\":\\"task.0192f4c8-4e7c-7d50-b13c-5eaf8a4d9c62\\",\\"contextId\\":\\"ctx.0192f4c8-3d6b-7c4f-a02b-4d9e7f3c8b51\\",\\"status\\":{\\"state\\":\\"TASK_STATE_WORKING\\"}}}","event":"message","id":"id","retry":1}\n\n';

        server
            .mockEndpoint()
            .post("/agentic/agents/agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40/a2a/message:stream")
            .header("A2A-Version", "1.0")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .sseBody(rawResponseBody)
            .build();

        const response = await client.agentic.agents.a2A.streamMessage("agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40", {
            message: {
                messageId: "msg.0192f4c8-5f8d-7e61-924d-6fb09b5ead73",
                role: "ROLE_USER",
                parts: [
                    {
                        text: "What is the ICD-10 code for asthma?",
                    },
                ],
            },
        });
        const events: unknown[] = [];
        for await (const event of response) {
            events.push(event);
        }
        expect(events).toEqual([
            {
                data: '{"task":{"id":"task.0192f4c8-4e7c-7d50-b13c-5eaf8a4d9c62","contextId":"ctx.0192f4c8-3d6b-7c4f-a02b-4d9e7f3c8b51","status":{"state":"TASK_STATE_WORKING"}}}',
                event: "message",
                id: "id",
                retry: 1,
            },
        ]);
    });

    test("streamMessage (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { message: { role: "ROLE_USER", parts: [{}, {}] } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agentic/agents/agentId/a2a/message:stream")
            .header("A2A-Version", "1.0")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.agents.a2A.streamMessage("agentId", {
                message: {
                    role: "ROLE_USER",
                    parts: [{}, {}],
                },
            });
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("streamMessage (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { message: { role: "ROLE_USER", parts: [{}, {}] } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agentic/agents/agentId/a2a/message:stream")
            .header("A2A-Version", "1.0")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.agents.a2A.streamMessage("agentId", {
                message: {
                    role: "ROLE_USER",
                    parts: [{}, {}],
                },
            });
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("streamMessage (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { message: { role: "ROLE_USER", parts: [{}, {}] } };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/agentic/agents/agentId/a2a/message:stream")
            .header("A2A-Version", "1.0")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.agents.a2A.streamMessage("agentId", {
                message: {
                    role: "ROLE_USER",
                    parts: [{}, {}],
                },
            });
        }).rejects.toThrow(Corti.NotFoundError);
    });
});
