// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface ListAlphaSectionsRequest {
    /** Filter sections by language (BCP 47 tag). Repeatable. */
    lang?: string | string[];
    /** Filter sections by label. Repeatable; matches sections that have any of the given labels. */
    label?: string | string[];
    /** Filter by publish status. Omit to return both published and unpublished items; set to `true` for published only, `false` for unpublished only. */
    published?: boolean;
}
