/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "12345678-90ab-cdef-gh12-34567890abc",
 *         body: {
 *             id: "id",
 *             name: "name",
 *             description: "description",
 *             systemPrompt: "systemPrompt"
 *         }
 *     }
 */
export interface AgentsUpdateRequest {
    /**
     * The identifier of the agent associated with the context.
     */
    id: string;
    body: Corti.AgentsAgent;
}
