/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../../../../index.js";

/**
 * @example
 *     {
 *         message: {
 *             role: "user",
 *             parts: [{
 *                     kind: "text",
 *                     text: "text"
 *                 }],
 *             messageId: "messageId",
 *             kind: "message"
 *         }
 *     }
 */
export interface AgentsMessageSendParams {
    message: Corti.AgentsMessage;
    configuration?: Corti.AgentsMessageSendConfiguration;
    /** Optional metadata that will be associated with the message. */
    metadata?: Record<string, unknown>;
}
