// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";
import { GuidedSectionListItem } from "../../../../../types/GuidedSectionListItem.js";

export const Response: core.serialization.Schema<
    serializers.documents.sections.list.Response.Raw,
    Corti.GuidedSectionListItem[]
> = core.serialization.list(GuidedSectionListItem);

export declare namespace Response {
    export type Raw = GuidedSectionListItem.Raw[];
}
