// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../../../../api/index.js";
import * as core from "../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../index.js";
import { GuidedSectionPolicy } from "../../../../../../../types/GuidedSectionPolicy.js";
import { GuidedSectionsCreatePolicyRequest } from "../../../../../../../types/GuidedSectionsCreatePolicyRequest.js";

export const Request: core.serialization.Schema<
    serializers.documents.sections.policies.create.Request.Raw,
    Corti.GuidedSectionsCreatePolicyRequest[]
> = core.serialization.list(GuidedSectionsCreatePolicyRequest);

export declare namespace Request {
    export type Raw = GuidedSectionsCreatePolicyRequest.Raw[];
}

export const Response: core.serialization.Schema<
    serializers.documents.sections.policies.create.Response.Raw,
    Corti.GuidedSectionPolicy[]
> = core.serialization.list(GuidedSectionPolicy);

export declare namespace Response {
    export type Raw = GuidedSectionPolicy.Raw[];
}
