// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../../../../api/index.js";
import * as core from "../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../index.js";
import { GuidedSectionVersion } from "../../../../../../../types/GuidedSectionVersion.js";

export const Response: core.serialization.Schema<
    serializers.documents.sections.versions.list.Response.Raw,
    Corti.GuidedSectionVersion[]
> = core.serialization.list(GuidedSectionVersion);

export declare namespace Response {
    export type Raw = GuidedSectionVersion.Raw[];
}
