// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../../../../api/index.js";
import * as core from "../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../index.js";
import { GuidedTemplatePolicy } from "../../../../../../../types/GuidedTemplatePolicy.js";
import { GuidedTemplatesCreatePolicyRequest } from "../../../../../../../types/GuidedTemplatesCreatePolicyRequest.js";

export const Request: core.serialization.Schema<
    serializers.documents.templates.policies.create.Request.Raw,
    Corti.GuidedTemplatesCreatePolicyRequest[]
> = core.serialization.list(GuidedTemplatesCreatePolicyRequest);

export declare namespace Request {
    export type Raw = GuidedTemplatesCreatePolicyRequest.Raw[];
}

export const Response: core.serialization.Schema<
    serializers.documents.templates.policies.create.Response.Raw,
    Corti.GuidedTemplatePolicy[]
> = core.serialization.list(GuidedTemplatePolicy);

export declare namespace Response {
    export type Raw = GuidedTemplatePolicy.Raw[];
}
