// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { AgentsMessage } from "../../../types/AgentsMessage.js";
import { AgentsTask } from "../../../types/AgentsTask.js";

export const AgentsMessageSendResponse: core.serialization.ObjectSchema<
    serializers.AgentsMessageSendResponse.Raw,
    Corti.AgentsMessageSendResponse
> = core.serialization.object({
    message: AgentsMessage.optional(),
    task: AgentsTask.optional(),
});

export declare namespace AgentsMessageSendResponse {
    export interface Raw {
        message?: AgentsMessage.Raw | null;
        task?: AgentsTask.Raw | null;
    }
}
