/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Corti from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { AgentsCreateExpert } from "../../../types/AgentsCreateExpert.js";
import { AgentsExpertReference } from "../../../types/AgentsExpertReference.js";

export const AgentsCreateAgentExpertsItem: core.serialization.Schema<
    serializers.AgentsCreateAgentExpertsItem.Raw,
    Corti.AgentsCreateAgentExpertsItem
> = core.serialization
    .union("type", {
        new: AgentsCreateExpert,
        reference: AgentsExpertReference,
    })
    .transform<Corti.AgentsCreateAgentExpertsItem>({
        transform: (value) => value,
        untransform: (value) => value,
    });

export declare namespace AgentsCreateAgentExpertsItem {
    export type Raw = AgentsCreateAgentExpertsItem.New | AgentsCreateAgentExpertsItem.Reference;

    export interface New extends AgentsCreateExpert.Raw {
        type: "new";
    }

    export interface Reference extends AgentsExpertReference.Raw {
        type: "reference";
    }
}
