// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const AgentsFilePartKind: core.serialization.Schema<
    serializers.agents.AgentsFilePartKind.Raw,
    Corti.agents.AgentsFilePartKind
> = core.serialization.enum_(["file"]);

export declare namespace AgentsFilePartKind {
    export type Raw = "file";
}
