// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const AgentsCreateExpertType: core.serialization.Schema<
    serializers.agents.AgentsCreateExpertType.Raw,
    Corti.agents.AgentsCreateExpertType
> = core.serialization.enum_(["new"]);

export declare namespace AgentsCreateExpertType {
    export type Raw = "new";
}
