/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Corti from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import { AgentsCreateExpert } from "../../../types/AgentsCreateExpert.js";
import { AgentsCreateExpertReference } from "../../../types/AgentsCreateExpertReference.js";

export const AgentsCreateAgentExpertsItem: core.serialization.Schema<
    serializers.AgentsCreateAgentExpertsItem.Raw,
    Corti.AgentsCreateAgentExpertsItem
> = core.serialization.undiscriminatedUnion([AgentsCreateExpert, AgentsCreateExpertReference]);

export declare namespace AgentsCreateAgentExpertsItem {
    export type Raw = AgentsCreateExpert.Raw | AgentsCreateExpertReference.Raw;
}
