// This file was auto-generated by Fern from our API Definition.

import * as Corti from "../../../src/api/index";
import { CortiClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";
import { mockOAuth } from "../mockAuth";

describe("ArtifactsClient", () => {
    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = {
            artifactId: "art.0192f4c8-6a9e-7f72-a35e-70c1ac6fbe84",
            name: "icd10-result",
            description: "description",
            extensions: ["extensions"],
            metadata: { key: "value" },
            parts: [
                {
                    text: "J45.909",
                    data: { key: "value" },
                    filename: "filename",
                    mediaType: "mediaType",
                    raw: "raw",
                    url: "url",
                    metadata: { key: "value" },
                },
            ],
        };

        server
            .mockEndpoint()
            .get(
                "/v2/agentic/contexts/ctx.0192f4c8-3d6b-7c4f-a02b-4d9e7f3c8b51/tasks/task.0192f4c8-4e7c-7d50-b13c-5eaf8a4d9c62/artifacts/art.0192f4c8-6a9e-7f72-a35e-70c1ac6fbe84",
            )
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentic.artifacts.get(
            "ctx.0192f4c8-3d6b-7c4f-a02b-4d9e7f3c8b51",
            "task.0192f4c8-4e7c-7d50-b13c-5eaf8a4d9c62",
            "art.0192f4c8-6a9e-7f72-a35e-70c1ac6fbe84",
        );
        expect(response).toEqual({
            artifactId: "art.0192f4c8-6a9e-7f72-a35e-70c1ac6fbe84",
            name: "icd10-result",
            description: "description",
            extensions: ["extensions"],
            metadata: {
                key: "value",
            },
            parts: [
                {
                    text: "J45.909",
                    data: {
                        key: "value",
                    },
                    filename: "filename",
                    mediaType: "mediaType",
                    raw: "raw",
                    url: "url",
                    metadata: {
                        key: "value",
                    },
                },
            ],
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/agentic/contexts/contextId/tasks/taskId/artifacts/artifactId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.artifacts.get("contextId", "taskId", "artifactId");
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/agentic/contexts/contextId/tasks/taskId/artifacts/artifactId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.artifacts.get("contextId", "taskId", "artifactId");
        }).rejects.toThrow(Corti.ForbiddenError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/agentic/contexts/contextId/tasks/taskId/artifacts/artifactId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.artifacts.get("contextId", "taskId", "artifactId");
        }).rejects.toThrow(Corti.NotFoundError);
    });
});
