// This file was auto-generated by Fern from our API Definition.

import * as Corti from "../../../src/api/index";
import { CortiClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";
import { mockOAuth } from "../mockAuth";

describe("ModelsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = {
            data: [
                { id: "corti-s1", created: 1782722183, ownedBy: "Corti" },
                { id: "corti-s1-instant", created: 1783330290, ownedBy: "Corti" },
                { id: "corti-s1-mini", created: 1783326675, ownedBy: "Corti" },
            ],
        };

        server.mockEndpoint().get("/agentic/models").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agentic.models.list();
        expect(response).toEqual({
            data: [
                {
                    id: "corti-s1",
                    created: 1782722183,
                    ownedBy: "Corti",
                },
                {
                    id: "corti-s1-instant",
                    created: 1783330290,
                    ownedBy: "Corti",
                },
                {
                    id: "corti-s1-mini",
                    created: 1783326675,
                    ownedBy: "Corti",
                },
            ],
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/agentic/models").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agentic.models.list();
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { error: { code: "code", message: "message" } };

        server.mockEndpoint().get("/agentic/models").respondWith().statusCode(503).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agentic.models.list();
        }).rejects.toThrow(Corti.ServiceUnavailableError);
    });
});
