// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../../../../api/index.js";
import * as core from "../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../index.js";
import { TemplateInstructions } from "../../../../../../../types/TemplateInstructions.js";
import { TemplateVersionSectionRequest } from "../../../../../../../types/TemplateVersionSectionRequest.js";

export const CreateTemplateVersionRequestGeneration: core.serialization.ObjectSchema<
    serializers.documents.templates.CreateTemplateVersionRequestGeneration.Raw,
    Corti.documents.templates.CreateTemplateVersionRequestGeneration
> = core.serialization.object({
    instructions: TemplateInstructions,
    sections: core.serialization.list(TemplateVersionSectionRequest).optional(),
});

export declare namespace CreateTemplateVersionRequestGeneration {
    export interface Raw {
        instructions: TemplateInstructions.Raw;
        sections?: TemplateVersionSectionRequest.Raw[] | null;
    }
}
