/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The kind of the object, always "message".
 */
export type AgentsMessageKind = "message";
export const AgentsMessageKind = {
    Message: "message",
} as const;
