// This file was auto-generated by Fern from our API Definition.

/** Type of authorization used by the MCP server. */
export const AgentsCreateMcpServerAuthorizationType = {
    None: "none",
    Bearer: "bearer",
    Inherit: "inherit",
    Oauth20: "oauth2.0",
} as const;
export type AgentsCreateMcpServerAuthorizationType =
    (typeof AgentsCreateMcpServerAuthorizationType)[keyof typeof AgentsCreateMcpServerAuthorizationType];
