/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A reference to an expert, either id or name must be provided. If both are passed, the id will be used. An optional systemPrompt can be provided when creating an expert from the registry and will be returned on the reference.
 */
export interface AgentsExpertReference {
    type: "reference";
    /** The unique identifier of the expert. */
    id?: string;
    /** The name of the expert. */
    name?: string;
    /** Optional system prompt that defines the expert's behavior and expectations when created from the registry. */
    systemPrompt?: string;
}
