// This file was auto-generated by Fern from our API Definition.

/** The role of the message sender. */
export const AgentsMessageRole = {
    User: "user",
    Agent: "agent",
} as const;
export type AgentsMessageRole = (typeof AgentsMessageRole)[keyof typeof AgentsMessageRole];
