/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface AgentsContext {
    /** The context ID. */
    id?: string;
    items?: Corti.AgentsContextItemsItem[];
}
