// This file was auto-generated by Fern from our API Definition.

export interface AgenticAgentsAgentCardSignaturesItem {
    /** Base64url-encoded protected JWS header. */
    protected: string;
    /** Unprotected JWS header values. */
    header?: Record<string, unknown>;
    /** Base64url-encoded signature. */
    signature: string;
}
