// This file was auto-generated by Fern from our API Definition.

export const AgentsExpertReferenceType = {
    Reference: "reference",
} as const;
export type AgentsExpertReferenceType = (typeof AgentsExpertReferenceType)[keyof typeof AgentsExpertReferenceType];
