// This file was auto-generated by Fern from our API Definition.

/**
 * Publishing organization and URL.
 */
export interface AgentCardResponseProvider {
    /** Publishing organization name. */
    organization?: string;
    /** Publishing organization URL. */
    url?: string;
}
