// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

export interface AgentsRegistryMcpServer {
    /** Name of the MCP server. */
    name: string;
    /** Type of authorization used by the MCP server. */
    authorizationType: Corti.AgentsRegistryMcpServerAuthorizationType;
}
