// This file was auto-generated by Fern from our API Definition.

/** The kind of the object, always "message". */
export const AgentsMessageKind = {
    Message: "message",
} as const;
export type AgentsMessageKind = (typeof AgentsMessageKind)[keyof typeof AgentsMessageKind];
