/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A reference to an expert returned by the API. The expert's id and name are always provided. systemPrompt is included only when a registry expert was created with a custom system prompt.
 */
export interface AgentsExpertReference {
    type: "reference";
    /** The unique identifier of the expert. */
    id: string;
    /** The name of the expert. */
    name: string;
    /** Optional. Additional system instructions appended to the default system prompt when creating an expert from the registry, extending the expert's behavior. */
    systemPrompt?: string;
}
