/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface AgentsTaskStatusUpdateEvent {
    /** Unique identifier for the task. */
    taskId: string;
    /** Identifier for the context (thread) in which the task is created. */
    contextId: string;
    /** The kind of the object, always "status-update". */
    kind: "status-update";
    status: Corti.AgentsTaskStatus;
    /** Indicates whether this is the final status update for the task. */
    final: boolean;
    /** Additional metadata for the status update event. */
    metadata?: Record<string, unknown>;
}
