/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface AgentsDataPart {
    /** The kind of the part, always "data". */
    kind: Corti.AgentsDataPartKind;
    /** JSON data payload. */
    data: Record<string, unknown>;
    /** Additional metadata for the data part. */
    metadata?: Record<string, unknown>;
}
