/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface AgentsCreateExpert {
    type: "new";
    /** The name of the expert. Must be unique. */
    name: string;
    /** A brief description of the expert's capabilities. */
    description: string;
    /** Optional system prompt that defines the expert's behavior and expectations. */
    systemPrompt?: string;
    /** A list of MCP servers that the expert can call. If omitted, the expert can't call any MCP Servers. */
    mcpServers?: Corti.AgentsCreateMcpServer[];
}
