// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

/**
 * Exactly one of `task` or `message` is present.
 */
export interface AgenticAgentsSendMessageResponse {
    task?: Corti.CommonTaskResponse;
    message?: Corti.CommonMessage;
}
