// This file was auto-generated by Fern from our API Definition.

/**
 * - `ephemeral` — short-lived; expired automatically.
 * - `persistent` — retained until explicitly deleted.
 */
export const AgentsLifecycle = {
    Ephemeral: "ephemeral",
    Persistent: "persistent",
} as const;
export type AgentsLifecycle = (typeof AgentsLifecycle)[keyof typeof AgentsLifecycle];
