/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The transport protocol used to communicate with the agent.
 */
export type AgentsTransportProtocol = "JSONRPC" | "GRPC" | "HTTP+JSON";
export const AgentsTransportProtocol = {
    Jsonrpc: "JSONRPC",
    Grpc: "GRPC",
    HttpJson: "HTTP+JSON",
} as const;
