// This file was auto-generated by Fern from our API Definition.

/**
 * OAuth 2.0 client credentials token request (form body).
 */
export interface AuthTokenRequest {
    /** Client identifier. */
    clientId: string;
    /** Client secret. */
    clientSecret: string;
    grantType: "client_credentials";
    scope: "openid";
}
