/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

/**
 * Predicted or candidate code record.
 */
export interface CodesGeneralReadResponse {
    /** The coding system used */
    system: Corti.CommonCodingSystemEnum;
    /** The medical code */
    code: string;
    /** Description of the medical code */
    display: string;
    /** The evidence for the prediction */
    evidences?: Corti.CodesGeneralReadResponseEvidencesItem[];
    /** Modifier codes associated with the code */
    modifiers?: Corti.CodesGeneralReadResponseModifiersItem[];
    /** Codes the model also considered for this prediction. */
    alternatives?: Corti.CodesGeneralReadResponseAlternativesItem[];
}
