// This file was auto-generated by Fern from our API Definition.

/** `all` ANDs conditions (every condition must match). `any` ORs them (at least one must match). Omit when `conditions` has a single element. */
export const CodesConditionGroupMatch = {
    All: "all",
    Any: "any",
} as const;
export type CodesConditionGroupMatch = (typeof CodesConditionGroupMatch)[keyof typeof CodesConditionGroupMatch];
