// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

/**
 * System-scoped filter to restrict the set of codes the model can predict for a single coding system.
 */
export interface CodesSystemFilter {
    /** The coding system this filter applies to. Must match one of the systems in the `system` field. */
    systemId: string;
    /** Codes matching this group of conditions are eligible. Omitted means every code in the system is eligible. */
    include?: Corti.CodesConditionGroup;
    /** Codes matching this group of conditions are removed from the eligible set. Omitted means nothing is removed. */
    exclude?: Corti.CodesConditionGroup;
}
