// This file was auto-generated by Fern from our API Definition.

/**
 * The connector discriminator. v2 ships `registry`, `mcp`, `agent`,
 * `a2a`, and `schema`; `openapi` and `custom` are reserved for future
 * minor versions.
 */
export const CommonConnectorType = {
    Registry: "registry",
    Mcp: "mcp",
    Agent: "agent",
    A2A: "a2a",
    Schema: "schema",
} as const;
export type CommonConnectorType = (typeof CommonConnectorType)[keyof typeof CommonConnectorType];
