// This file was auto-generated by Fern from our API Definition.

/**
 * Total number of items matching the query, when known. Not currently populated by the server; treat as absent.
 */
export type CommonTotalSize = number;
