// This file was auto-generated by Fern from our API Definition.

/** The author of a message. */
export const CommonRole = {
    RoleUser: "ROLE_USER",
    RoleAgent: "ROLE_AGENT",
} as const;
export type CommonRole = (typeof CommonRole)[keyof typeof CommonRole];
