// This file was auto-generated by Fern from our API Definition.

/** The lifecycle state of a task. */
export const CommonTaskState = {
    TaskStateSubmitted: "TASK_STATE_SUBMITTED",
    TaskStateWorking: "TASK_STATE_WORKING",
    TaskStateCompleted: "TASK_STATE_COMPLETED",
    TaskStateFailed: "TASK_STATE_FAILED",
    TaskStateCanceled: "TASK_STATE_CANCELED",
    TaskStateInputRequired: "TASK_STATE_INPUT_REQUIRED",
    TaskStateRejected: "TASK_STATE_REJECTED",
    TaskStateAuthRequired: "TASK_STATE_AUTH_REQUIRED",
} as const;
export type CommonTaskState = (typeof CommonTaskState)[keyof typeof CommonTaskState];
