// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

/**
 * A named output produced by a task.
 */
export interface CommonArtifactResponse {
    artifactId: Corti.CommonArtifactIdValue;
    /** Optional artifact name. */
    name?: string;
    /** A human-readable description of the artifact. */
    description?: string;
    /** URIs of extensions that contributed to this artifact. */
    extensions?: string[];
    /** Optional metadata included with the artifact. */
    metadata?: Record<string, unknown>;
    /** Content parts of the artifact. */
    parts: Corti.CommonPart[];
}
