// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

/**
 * An A2A task — a unit of agent work with status, history, and artifacts.
 */
export interface CommonTaskResponse {
    id: Corti.CommonTaskIdValue;
    contextId: Corti.CommonContextIdValue;
    status: Corti.CommonTaskStatus;
    /** Messages exchanged during the task, oldest first. */
    history?: Corti.CommonMessage[];
    /** Artifacts produced by the task. */
    artifacts?: Corti.CommonArtifactResponse[];
    /** Task metadata, including `corti.usage` credit accounting. Populated by both the REST and JSON-RPC v2 bindings; the deprecated v1 bindings do not include it. */
    metadata?: Corti.CommonTaskMetadata;
}
