// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

/**
 * Request body for attaching an MCP connector.
 */
export interface CommonMcpConnectorCreate {
    type: "mcp";
    /** Display name for the MCP connector. */
    name: string;
    /** MCP server endpoint URL. */
    url: string;
    /** Whether the connector is active for invocations. */
    enabled?: boolean;
    auth?: Corti.CommonConnectorAuth;
}
