// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

/**
 * Free-form A2A task metadata. Corti's first-party keys live under the
 * `corti` namespace. Token and credit accounting is carried under
 * `corti.usage`. Arbitrary additional keys are permitted.
 */
export interface CommonTaskMetadata {
    corti?: Corti.CommonCortiMetadata;
    /** Accepts any additional properties */
    [key: string]: any;
}
