// This file was auto-generated by Fern from our API Definition.

/**
 * Artifact identifier. Accepts `art.<uuidv7>` or a bare UUIDv7 on input; always returned prefixed.
 */
export type CommonArtifactIdValue = string;
