// This file was auto-generated by Fern from our API Definition.

export interface CommonTextContext {
    type: "text";
    /** A text string to be used as input to the model. */
    text: string;
}
