// This file was auto-generated by Fern from our API Definition.

/**
 * Opaque cursor to request the next page, or `null` if there are no more pages.
 */
export type CommonNextPageToken = string | null;
