// This file was auto-generated by Fern from our API Definition.

export const CommonCodingSystemEnum = {
    Icd10CmInpatient: "icd10cm-inpatient",
    Icd10CmOutpatient: "icd10cm-outpatient",
    Icd10Pcs: "icd10pcs",
    Cpt: "cpt",
} as const;
export type CommonCodingSystemEnum = (typeof CommonCodingSystemEnum)[keyof typeof CommonCodingSystemEnum];
