// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

/**
 * A context together with its tasks. Returned by `GET /contexts/{id}`.
 * Tasks are ordered oldest first and each carries its full message
 * `history` — the user's prompt for a task is the `ROLE_USER` message
 * within that task's history.
 */
export interface ContextsDetailResponse extends Corti.Contexts {
    /** The context's tasks, oldest first, each with full message history. */
    tasks: Corti.CommonTaskResponse[];
}
