// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

/**
 * A page of traces for a context in OpenInference format. Traces are
 * ordered newest-first.
 */
export interface ContextsTraceResponse {
    /** Traces for the context, newest first. */
    traces: Corti.ContextsTraceItem[];
    nextPageToken?: Corti.CommonNextPageToken | null;
    totalSize?: Corti.CommonTotalSize;
}
