// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

/**
 * Response when a document is generated but not saved (retention policy `none`).
 */
export interface CreateEphemeralDocumentResponse {
    document: Corti.EphemeralDocument;
    usageInfo: Corti.CommonUsageInfo;
}
