// This file was auto-generated by Fern from our API Definition.

/** The type of context data that will be used in the request: `Facts`, `Transcript`, or `String`. */
export const DocumentsContextWithTranscriptType = {
    Transcript: "transcript",
} as const;
export type DocumentsContextWithTranscriptType =
    (typeof DocumentsContextWithTranscriptType)[keyof typeof DocumentsContextWithTranscriptType];
