/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface DocumentsTemplateWithSectionIds {
    /** An array of section IDs. */
    sectionIds: Corti.Uuid[];
    /** The name of the document. */
    documentName?: string;
    /** Any additional instructions to be considered during document generation. */
    additionalInstructions?: string;
}
