// This file was auto-generated by Fern from our API Definition.

export interface DocumentsContextWithString {
    /** The type of context data that will be used in the request: `Facts`, `Transcript`, or `String`. */
    type: "string";
    /** String data can include any text to be reasoned over for document generation: Transcript text, facts, or other narrative information. */
    data: string;
}
