// This file was auto-generated by Fern from our API Definition.

/** The type of context data that will be used in the request: `Facts`, `Transcript`, or `String`. */
export const DocumentsContextWithStringType = {
    String: "string",
} as const;
export type DocumentsContextWithStringType =
    (typeof DocumentsContextWithStringType)[keyof typeof DocumentsContextWithStringType];
