/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../index.js";

export interface DocumentsTemplateWithSections {
    sections?: Corti.DocumentsSectionOverride[];
    /** The name of the document. */
    documentName?: string;
    /** Override to use for the template-level additional instructions. */
    additionalInstructionsOverride?: string;
}
