// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

export interface FactsCreateInput {
    /** The text content of the fact. */
    text: string;
    /** The key identifying the group to which the fact belongs. */
    group: string;
    /** The origin of the fact, such as 'USER' or 'SYSTEM'. */
    source?: Corti.CommonSourceEnum;
}
