// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

/**
 * The original rating supplied by the customer.
 */
export interface FeedbackRating {
    scale: Corti.FeedbackRatingScale;
    /** The rating value on the selected scale. */
    value: number;
}
