// This file was auto-generated by Fern from our API Definition.

/** The kind of access policy. */
export const GuidedTemplatesCreatePolicyRequestKind = {
    Project: "project",
    Customers: "customers",
} as const;
export type GuidedTemplatesCreatePolicyRequestKind =
    (typeof GuidedTemplatesCreatePolicyRequestKind)[keyof typeof GuidedTemplatesCreatePolicyRequestKind];
