// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

export interface GuidedTemplateRef {
    /** The UUID of a stored template. */
    templateId: string;
    /** Optional explicit template version. Defaults to the template's published version when omitted. */
    templateVersionId?: string | null;
    /** Runtime overrides applied on top of the resolved template. When present, a new auto-generated template is persisted with `inheritedFromId` pointing at the base template. */
    overrides?: Corti.GuidedTemplateOverrides;
}
