// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

export interface GuidedSectionGeneration {
    /** The heading of this section. Passed to the LLM. */
    heading: string;
    /** The prompt instructions for this section. */
    instructions: Corti.GuidedSectionInstructions;
    outputSchema: Corti.OutputSchema;
}
