// This file was auto-generated by Fern from our API Definition.

/**
 * Minimal fact shape. Only `text` is required.
 */
export interface GuidedDocumentFactMinimal {
    /** The text of the fact. */
    text: string;
    /** The group to which the fact belongs. */
    group?: string;
}
