// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

export interface GuidedSectionVersion {
    /** The UUID of the section version. */
    id: string;
    /** Starts at 0 and auto-increments. */
    versionNumber: number;
    /** Present when the section version has been deleted. */
    deletedAt?: Date | null;
    generation: Corti.GuidedSectionGeneration;
}
