// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

export interface GuidedTemplateGeneration {
    instructions: Corti.GuidedTemplateInstructions;
    /** Populated only on GET /documents/templates/{templateID}/versions/{versionID}; omitted from list responses. */
    sections?: Corti.GuidedSection[];
}
