// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

/**
 * Generate a document by assembling a template from existing stored sections, with input context drawn implicitly from an existing interaction's facts and transcripts. The resulting template aggregate is auto-saved and can be referenced in future calls.
 */
export interface GuidedDocumentByAssemblyWithInteractionId {
    /** All facts and transcripts already attached to the referenced interaction are passed implicitly as input context. */
    interactionId: string;
    /** Assemble a template from existing stored sections. */
    assemblyTemplate: Corti.GuidedAssemblyRequest;
}
