// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

/**
 * Creates a template from scratch. The template fully specifies its own sections and optional template-level instructions.
 */
export interface GuidedTemplatesCreateFromScratchRequest extends Corti.GuidedTemplatesCreateBase {
    generation: Corti.GuidedTemplatesCreateFromScratchRequestGeneration;
}
