// This file was auto-generated by Fern from our API Definition.

/** Whether this section was created by the user, a project-related API Client or is a Corti standard resource. */
export const GuidedSectionListItemSource = {
    User: "user",
    Corti: "corti",
    Project: "project",
} as const;
export type GuidedSectionListItemSource =
    (typeof GuidedSectionListItemSource)[keyof typeof GuidedSectionListItemSource];
