// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

/**
 * A generated document that was not saved to the database.
 */
export interface GuidedEphemeralDocument {
    name: string;
    templateId: string;
    templateVersionId: string;
    /** The BCP 47 language tag of the generated output. */
    language: string;
    /** The interaction whose context was used to generate this document, if supplied. */
    interactionId?: string | null;
    stringDocument: Record<string, string>;
    structuredDocument?: Record<string, unknown> | null;
    /** Key/value labels attached to this document. */
    labels: Corti.GuidedLabel[];
}
