// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

export interface GuidedTemplatesCreateBase {
    /** The name of this template. Not passed to the LLM. */
    name: string;
    /** A description for this template. Not passed to the LLM. */
    description?: string;
    /** BCP 47 language tags this template has been tweaked for (e.g. `["fr", "de", "en-GB"]`). */
    languages?: string[];
    /** ISO 3166-1 alpha-3 country codes this template has been tweaked for (e.g. `["BEL"]`). */
    regions?: string[];
    /** Clinical specialties this template has been tweaked for. */
    specialties?: string[];
    /** Labels work as query param filter in the LIST /templates endpoint. */
    labels?: Corti.GuidedLabel[];
    /** Defaults to true when omitted. Set this to false if you do not want the template to automatically show up in LIST templates. */
    publish?: boolean;
}
