// This file was auto-generated by Fern from our API Definition.

export const InteractionsEncounterTypeEnum = {
    FirstConsultation: "first_consultation",
    Consultation: "consultation",
    Emergency: "emergency",
    Inpatient: "inpatient",
    Outpatient: "outpatient",
} as const;
export type InteractionsEncounterTypeEnum =
    (typeof InteractionsEncounterTypeEnum)[keyof typeof InteractionsEncounterTypeEnum];
