// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

export interface LanguagesEndpoints {
    /** Streams endpoint with its supported attributes. */
    streams: Corti.LanguagesEndpointAttributes;
    /** Transcribe endpoint with its supported attributes. */
    transcribe: Corti.LanguagesEndpointAttributes;
    /** Transcripts endpoint with its supported attributes. */
    transcripts: Corti.LanguagesEndpointAttributes;
}
