// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

export type OutputSchema =
    | Corti.StringNode
    | Corti.IntegerNode
    | Corti.FloatNode
    | Corti.BoolNode
    | Corti.DictNode
    | Corti.ListNode;
