// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

export interface RecordingsCreateResponse {
    /** The unique identifier for the created recording. */
    recordingId: Corti.Uuid;
}
