// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

/**
 * A discoverable, pre-built connector offered by the platform registry.
 * Only `id`, `type`, `name`, `title`, `description`, and `configSchema` are populated by the server today. `version`, `provider`, `capabilities`, `tags`, and `documentationUrl` are declared for forward compatibility but are not yet returned.
 */
export interface RegistryConnectorResponse {
    /** Stable, namespaced registry identifier; use as a `registry` connector's `name`. */
    id: string;
    /** The connector kind this entry provisions when attached to an agent. */
    type: Corti.CommonConnectorType;
    /** Programmatic name (MCP convention). */
    name: string;
    /** Human-readable display name (MCP convention). */
    title?: string;
    /** Description for list and detail views. May contain CommonMark. */
    description?: string;
    /** Latest published version (SemVer recommended). */
    version?: string;
    /** Display icons (MCP convention). */
    icons?: Corti.RegistryIcon[];
    /** Name of the publishing organisation. */
    provider?: string;
    /** Connector homepage (MCP convention). */
    websiteUrl?: string;
    /** Documentation URL for the connector. */
    documentationUrl?: string;
    capabilities?: Corti.RegistryConnectorCapabilities;
    /** Keywords for search and filtering. */
    tags?: string[];
    /** JSON Schema (draft 2020-12) describing the connector's accepted `config`. */
    configSchema?: Record<string, unknown>;
}
