// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

/**
 * Patches a section's content at link time without mutating the underlying section. Override semantics are per-field for instructions (any field you omit is inherited from the parent's published version) and wholesale for `outputSchema` (whatever you submit fully replaces the parent schema). The same applies when a section is forked via `inheritFromId`.
 */
export interface SectionOverrides {
    /** When provided, replaces the section's title for this call. */
    title?: string | null;
    instructions?: Corti.SectionInstructionsOverride;
    /** When provided, fully replaces the parent's output schema. */
    outputSchema?: Corti.OutputSchema;
}
