// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

export interface StreamConfigMessage {
    type: Corti.StreamConfigMessageType;
    configuration: Corti.StreamConfig;
}
