// This file was auto-generated by Fern from our API Definition.

export interface TemplateVersionSectionRef {
    /** The UUID of the section linked to this template version. */
    sectionId: string;
    /** The ordering position of the section within the template version. */
    orderIndex: number;
}
