/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Configures the approach and underlying system prompt that govern how the LLM generates documentation.
 */
export type TemplatesDocumentationModeEnum = "global_sequential" | "routed_parallel";
export const TemplatesDocumentationModeEnum = {
    GlobalSequential: "global_sequential",
    RoutedParallel: "routed_parallel",
} as const;
