/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Text {
    /** A string text context that can be used to provide additional information. */
    text: string;
}
