// This file was auto-generated by Fern from our API Definition.

export interface TranscribeConfigKeytermsTermsItem {
    /** The word to be recognized, defined in its expected written form. A defined `term` is limited to a length of 50 characters. */
    term: string;
}
