// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

export interface TranscribeCommandVariable {
    /** Define the variable used in command phrases. */
    key: string;
    /** Variable type. Use `enum` to define a fixed list of values that can be recognized for the variable. Use `wildcard` to recognize any undefined, open-ended free-text utterance. When using `wildcard`, the phrase must include a literal trigger word before the wildcard variable (a phrase may not begin with a wildcard variable), and multiple wildcard variables in a single phrase must be separated by a non-empty literal string (e.g. `select {text1} end select {text2}` is valid; `{text1} {text2}` is not). */
    type: Corti.TranscribeCommandVariableType;
    /** List of values that should be recognized for the defined variable. Required when `type` is `enum`. Not used (and ignored) when `type` is `wildcard`. */
    enum?: string[];
}
