// This file was auto-generated by Fern from our API Definition.

export const TranscriptsParticipantRoleEnum = {
    Doctor: "doctor",
    Patient: "patient",
    Multiple: "multiple",
} as const;
export type TranscriptsParticipantRoleEnum =
    (typeof TranscriptsParticipantRoleEnum)[keyof typeof TranscriptsParticipantRoleEnum];
