// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

export interface TranscriptsResponse {
    /** The unique identifier of the transcript. */
    id: Corti.Uuid;
    /** Additional information about the participants involved in the transcript. */
    metadata: Corti.TranscriptsMetadata;
    /** An array of transcripts. */
    transcripts: Corti.CommonTranscriptResponse[] | null;
    usageInfo: Corti.CommonUsageInfo;
    /** The unique identifier for the associated recording. */
    recordingId: Corti.Uuid;
    /** The current status of the transcript processing. */
    status: Corti.TranscriptsStatusEnum;
}
