// This file was auto-generated by Fern from our API Definition.

/** The type of audio quality or speech activity event */
export const TranscribeAudioEventDataEvent = {
    SpeechQualityIssueDetected: "speechQualityIssueDetected",
    SpeechQualityIssueRecovered: "speechQualityIssueRecovered",
    LongSilenceDetected: "longSilenceDetected",
    LongSilenceRecovered: "longSilenceRecovered",
} as const;
export type TranscribeAudioEventDataEvent =
    (typeof TranscribeAudioEventDataEvent)[keyof typeof TranscribeAudioEventDataEvent];
