// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

export interface TranscriptsData {
    /** Additional information about the participants involved in the transcript. */
    metadata: Corti.TranscriptsMetadata;
    /** An array of transcripts. */
    transcripts: Corti.CommonTranscriptResponse[];
}
