/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Variable type
 */
export type TranscribeCommandVariableType = "enum";
export const TranscribeCommandVariableType = {
    Enum: "enum",
} as const;
