// This file was auto-generated by Fern from our API Definition.

export interface TranscribeCommandVariable {
    /** Define the variable used in command phrases. */
    key: string;
    /** Variable type */
    type: "enum";
    /** List of values that should be recognized for the defined variable. */
    enum: string[];
}
