// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../index.js";

export interface TranscribeConfigStatusMessage {
    /** Configuration status result */
    type: Corti.TranscribeConfigStatusMessageType;
    /** Optional reason for rejection */
    reason?: string;
    /** Session identifier returned when configuration is accepted */
    sessionId: string;
}
