/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TranscribeErrorMessageType = "error";
export const TranscribeErrorMessageType = {
    Error: "error",
} as const;
