/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface FactsGenerateRequest {
    context?: Corti.FactsGenerateRequestContextItem[];
    /** The desired language for generated facts. */
    outputLanguage?: string;
    /** The primary language of the input, needed for verification before generation. */
    primaryLanguage?: string;
}
