/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../../../../index.js";

/**
 * @example
 *     {
 *         id: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
 *         factId: "f47ac10b-58cc-4372-a567-0e02b2c3d479"
 *     }
 */
export interface FactsUpdateRequest {
    /**
     * The unique identifier of the interaction. Must be a valid UUID.
     */
    id: Corti.Uuid;
    /**
     * The unique identifier of the fact to update. Must be a valid UUID.
     */
    factId: Corti.Uuid;
    /** The updated text of the fact. */
    text?: string;
    /** The updated group key for the fact. */
    group?: string;
    /** The updated origin of the fact. Set to 'USER' to indicate a change by an end-user. */
    source?: Corti.CommonSourceEnum;
    /** Set this to true if discarded by an end-user, then filter out from the document generation request. */
    isDiscarded?: boolean;
}
