// This file was auto-generated by Fern from our API Definition.

export const AuthGetTokenRequestGrantType = {
    ClientCredentials: "client_credentials",
    AuthorizationCode: "authorization_code",
    RefreshToken: "refresh_token",
} as const;
export type AuthGetTokenRequestGrantType =
    (typeof AuthGetTokenRequestGrantType)[keyof typeof AuthGetTokenRequestGrantType];
