// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const DocumentsCreateRequest: core.serialization.Schema<
    serializers.DocumentsCreateRequest.Raw,
    Corti.DocumentsCreateRequest
> = core.serialization.object({
    oneOf: core.serialization.unknown().optional(),
});

export declare namespace DocumentsCreateRequest {
    export interface Raw {
        oneOf?: unknown | null;
    }
}
