// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../../../../api/index.js";
import * as core from "../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../index.js";
import { GuidedShallowTemplateVersionResponse } from "../../../../../../../types/GuidedShallowTemplateVersionResponse.js";

export const Response: core.serialization.Schema<
    serializers.documents.templates.versions.list.Response.Raw,
    Corti.GuidedShallowTemplateVersionResponse[]
> = core.serialization.list(GuidedShallowTemplateVersionResponse);

export declare namespace Response {
    export type Raw = GuidedShallowTemplateVersionResponse.Raw[];
}
