// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";
import { GuidedTemplateListItem } from "../../../../../types/GuidedTemplateListItem.js";

export const Response: core.serialization.Schema<
    serializers.documents.templates.list.Response.Raw,
    Corti.GuidedTemplateListItem[]
> = core.serialization.list(GuidedTemplateListItem);

export declare namespace Response {
    export type Raw = GuidedTemplateListItem.Raw[];
}
