// This file was auto-generated by Fern from our API Definition.

export const LanguagesListRequestEndpoint = {
    Streams: "streams",
    Transcribe: "transcribe",
    Transcripts: "transcripts",
} as const;
export type LanguagesListRequestEndpoint =
    (typeof LanguagesListRequestEndpoint)[keyof typeof LanguagesListRequestEndpoint];
