/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index.js";
import * as Corti from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";

export const GetTokenAuthRequest: core.serialization.Schema<
    serializers.GetTokenAuthRequest.Raw,
    Corti.GetTokenAuthRequest
> = core.serialization.object({
    clientId: core.serialization.property("client_id", core.serialization.string()),
    clientSecret: core.serialization.property("client_secret", core.serialization.string().optional()),
});

export declare namespace GetTokenAuthRequest {
    export interface Raw {
        client_id: string;
        client_secret?: string | null;
    }
}
