// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../../index.js";

/**
 * @example
 *     {
 *         id: "1",
 *         method: "SendMessage",
 *         params: {
 *             "message": {
 *                 "role": "ROLE_USER",
 *                 "messageId": "msg.0192f4c8-5f8d-7e61-924d-6fb09b5ead73",
 *                 "parts": [
 *                     {
 *                         "text": "Code this encounter."
 *                     }
 *                 ]
 *             }
 *         }
 *     }
 */
export interface AgenticAgentsJsonRpcRequest {
    id: Corti.agentic.AgenticAgentsJsonRpcRequestId;
    /** JSON-RPC method name (PascalCase on the wire). */
    method: Corti.agentic.AgenticAgentsJsonRpcRequestMethod;
    /** JSON-RPC params object. */
    params?: Record<string, unknown>;
}
