/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index.js";
import * as Corti from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import { AgentsCreateAgentExpertsItem } from "../../types/AgentsCreateAgentExpertsItem.js";

export const AgentsCreateAgent: core.serialization.Schema<
    serializers.AgentsCreateAgent.Raw,
    Omit<Corti.AgentsCreateAgent, "ephemeral">
> = core.serialization.object({
    name: core.serialization.string(),
    systemPrompt: core.serialization.string().optional(),
    description: core.serialization.string(),
    experts: core.serialization.list(AgentsCreateAgentExpertsItem).optional(),
});

export declare namespace AgentsCreateAgent {
    export interface Raw {
        name: string;
        systemPrompt?: string | null;
        description: string;
        experts?: AgentsCreateAgentExpertsItem.Raw[] | null;
    }
}
