// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { AgentsCreateMcpServer } from "../../../../types/AgentsCreateMcpServer.js";
import { AgentsUpdateAgentExpertsItem } from "../../types/AgentsUpdateAgentExpertsItem.js";

export const AgentsUpdateAgent: core.serialization.Schema<serializers.AgentsUpdateAgent.Raw, Corti.AgentsUpdateAgent> =
    core.serialization.object({
        name: core.serialization.string().optional(),
        systemPrompt: core.serialization.string().optional(),
        description: core.serialization.string().optional(),
        experts: core.serialization.list(AgentsUpdateAgentExpertsItem).optional(),
        mcpServers: core.serialization.list(AgentsCreateMcpServer).optional(),
    });

export declare namespace AgentsUpdateAgent {
    export interface Raw {
        name?: string | null;
        systemPrompt?: string | null;
        description?: string | null;
        experts?: AgentsUpdateAgentExpertsItem.Raw[] | null;
        mcpServers?: AgentsCreateMcpServer.Raw[] | null;
    }
}
