// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { AgentsMessage } from "../../../../types/AgentsMessage.js";
import { AgentsMessageSendConfiguration } from "../../../../types/AgentsMessageSendConfiguration.js";

export const AgentsMessageSendParams: core.serialization.Schema<
    serializers.AgentsMessageSendParams.Raw,
    Omit<Corti.AgentsMessageSendParams, "id">
> = core.serialization.object({
    message: AgentsMessage,
    configuration: AgentsMessageSendConfiguration.optional(),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace AgentsMessageSendParams {
    export interface Raw {
        message: AgentsMessage.Raw;
        configuration?: AgentsMessageSendConfiguration.Raw | null;
        metadata?: Record<string, unknown> | null;
    }
}
