// This file was auto-generated by Fern from our API Definition.

/** JSON-RPC method name (PascalCase on the wire). */
export const AgenticAgentsJsonRpcRequestMethod = {
    SendMessage: "SendMessage",
    SendStreamingMessage: "SendStreamingMessage",
    GetTask: "GetTask",
    ListTasks: "ListTasks",
    CancelTask: "CancelTask",
    SubscribeToTask: "SubscribeToTask",
} as const;
export type AgenticAgentsJsonRpcRequestMethod =
    (typeof AgenticAgentsJsonRpcRequestMethod)[keyof typeof AgenticAgentsJsonRpcRequestMethod];
