// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgenticAgentsAgentCardSkillsItem: core.serialization.ObjectSchema<
    serializers.AgenticAgentsAgentCardSkillsItem.Raw,
    Corti.AgenticAgentsAgentCardSkillsItem
> = core.serialization.object({
    id: core.serialization.string(),
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
    tags: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace AgenticAgentsAgentCardSkillsItem {
    export interface Raw {
        id: string;
        name: string;
        description?: string | null;
        tags?: string[] | null;
    }
}
