// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentsCreateExpertType } from "./AgentsCreateExpertType.js";
import { AgentsCreateMcpServer } from "./AgentsCreateMcpServer.js";

export const AgentsCreateExpert: core.serialization.ObjectSchema<
    serializers.AgentsCreateExpert.Raw,
    Corti.AgentsCreateExpert
> = core.serialization.object({
    type: AgentsCreateExpertType,
    name: core.serialization.string(),
    description: core.serialization.string(),
    systemPrompt: core.serialization.string().optional(),
    mcpServers: core.serialization.list(AgentsCreateMcpServer).optional(),
});

export declare namespace AgentsCreateExpert {
    export interface Raw {
        type: AgentsCreateExpertType.Raw;
        name: string;
        description: string;
        systemPrompt?: string | null;
        mcpServers?: AgentsCreateMcpServer.Raw[] | null;
    }
}
