// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentsUsageMetrics: core.serialization.ObjectSchema<
    serializers.AgentsUsageMetrics.Raw,
    Corti.AgentsUsageMetrics
> = core.serialization.object({
    invocations: core.serialization.number(),
    uniqueContexts: core.serialization.number(),
});

export declare namespace AgentsUsageMetrics {
    export interface Raw {
        invocations: number;
        uniqueContexts: number;
    }
}
