// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentsMcpServerAuthorizationType: core.serialization.Schema<
    serializers.AgentsMcpServerAuthorizationType.Raw,
    Corti.AgentsMcpServerAuthorizationType
> = core.serialization.enum_(["none", "oauth2.0", "oauth2.1"]);

export declare namespace AgentsMcpServerAuthorizationType {
    export type Raw = "none" | "oauth2.0" | "oauth2.1";
}
