/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { AgentsTextPartKind } from "./AgentsTextPartKind.js";

export const AgentsTextPart: core.serialization.ObjectSchema<serializers.AgentsTextPart.Raw, Corti.AgentsTextPart> =
    core.serialization.object({
        kind: AgentsTextPartKind,
        text: core.serialization.string(),
        metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    });

export declare namespace AgentsTextPart {
    export interface Raw {
        kind: AgentsTextPartKind.Raw;
        text: string;
        metadata?: Record<string, unknown> | null;
    }
}
