// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgenticFeedbackRatingScale } from "./AgenticFeedbackRatingScale.js";

export const AgenticFeedbackRating: core.serialization.ObjectSchema<
    serializers.AgenticFeedbackRating.Raw,
    Corti.AgenticFeedbackRating
> = core.serialization.object({
    scale: AgenticFeedbackRatingScale,
    value: core.serialization.number(),
});

export declare namespace AgenticFeedbackRating {
    export interface Raw {
        scale: AgenticFeedbackRatingScale.Raw;
        value: number;
    }
}
