/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { AgentsAgentReferenceType } from "./AgentsAgentReferenceType.js";

export const AgentsAgentReference: core.serialization.ObjectSchema<
    serializers.AgentsAgentReference.Raw,
    Corti.AgentsAgentReference
> = core.serialization.object({
    type: AgentsAgentReferenceType,
    id: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
});

export declare namespace AgentsAgentReference {
    export interface Raw {
        type: AgentsAgentReferenceType.Raw;
        id?: string | null;
        name?: string | null;
    }
}
