// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgenticAgentsAgentCardSupportedInterfacesItemProtocolBinding } from "./AgenticAgentsAgentCardSupportedInterfacesItemProtocolBinding.js";

export const AgenticAgentsAgentCardSupportedInterfacesItem: core.serialization.ObjectSchema<
    serializers.AgenticAgentsAgentCardSupportedInterfacesItem.Raw,
    Corti.AgenticAgentsAgentCardSupportedInterfacesItem
> = core.serialization.object({
    protocolBinding: AgenticAgentsAgentCardSupportedInterfacesItemProtocolBinding,
    protocolVersion: core.serialization.stringLiteral("1.0"),
    url: core.serialization.string(),
});

export declare namespace AgenticAgentsAgentCardSupportedInterfacesItem {
    export interface Raw {
        protocolBinding: AgenticAgentsAgentCardSupportedInterfacesItemProtocolBinding.Raw;
        protocolVersion: "1.0";
        url: string;
    }
}
