// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgenticAgentCardResponseCapabilities } from "./AgenticAgentCardResponseCapabilities.js";
import { AgenticAgentCardResponseProvider } from "./AgenticAgentCardResponseProvider.js";
import { AgenticAgentCardResponseSignaturesItem } from "./AgenticAgentCardResponseSignaturesItem.js";
import { AgenticAgentCardResponseSkillsItem } from "./AgenticAgentCardResponseSkillsItem.js";
import { AgenticAgentCardResponseSupportedInterfacesItem } from "./AgenticAgentCardResponseSupportedInterfacesItem.js";

export const AgenticAgentCardResponse: core.serialization.ObjectSchema<
    serializers.AgenticAgentCardResponse.Raw,
    Corti.AgenticAgentCardResponse
> = core.serialization.object({
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
    documentationUrl: core.serialization.string().optional(),
    iconUrl: core.serialization.string().optional(),
    version: core.serialization.string(),
    capabilities: AgenticAgentCardResponseCapabilities,
    defaultInputModes: core.serialization.list(core.serialization.string()).optional(),
    defaultOutputModes: core.serialization.list(core.serialization.string()).optional(),
    provider: AgenticAgentCardResponseProvider.optional(),
    securityRequirements: core.serialization
        .list(core.serialization.record(core.serialization.string(), core.serialization.unknown()))
        .optional(),
    securitySchemes: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    signatures: core.serialization.list(AgenticAgentCardResponseSignaturesItem).optional(),
    skills: core.serialization.list(AgenticAgentCardResponseSkillsItem).optional(),
    supportedInterfaces: core.serialization.list(AgenticAgentCardResponseSupportedInterfacesItem),
});

export declare namespace AgenticAgentCardResponse {
    export interface Raw {
        name: string;
        description?: string | null;
        documentationUrl?: string | null;
        iconUrl?: string | null;
        version: string;
        capabilities: AgenticAgentCardResponseCapabilities.Raw;
        defaultInputModes?: string[] | null;
        defaultOutputModes?: string[] | null;
        provider?: AgenticAgentCardResponseProvider.Raw | null;
        securityRequirements?: Record<string, unknown>[] | null;
        securitySchemes?: Record<string, unknown> | null;
        signatures?: AgenticAgentCardResponseSignaturesItem.Raw[] | null;
        skills?: AgenticAgentCardResponseSkillsItem.Raw[] | null;
        supportedInterfaces: AgenticAgentCardResponseSupportedInterfacesItem.Raw[];
    }
}
