// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgenticAgentsAgentCardSupportedInterfacesItemProtocolBinding: core.serialization.Schema<
    serializers.AgenticAgentsAgentCardSupportedInterfacesItemProtocolBinding.Raw,
    Corti.AgenticAgentsAgentCardSupportedInterfacesItemProtocolBinding
> = core.serialization.enum_(["JSONRPC", "HTTP+JSON"]);

export declare namespace AgenticAgentsAgentCardSupportedInterfacesItemProtocolBinding {
    export type Raw = "JSONRPC" | "HTTP+JSON";
}
