// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgenticContextsTraceItem } from "./AgenticContextsTraceItem.js";
import { CommonNextPageToken } from "./CommonNextPageToken.js";
import { CommonTotalSize } from "./CommonTotalSize.js";

export const AgenticContextsTraceResponse: core.serialization.ObjectSchema<
    serializers.AgenticContextsTraceResponse.Raw,
    Corti.AgenticContextsTraceResponse
> = core.serialization.object({
    traces: core.serialization.list(AgenticContextsTraceItem),
    nextPageToken: CommonNextPageToken.optionalNullable(),
    totalSize: CommonTotalSize.optional(),
});

export declare namespace AgenticContextsTraceResponse {
    export interface Raw {
        traces: AgenticContextsTraceItem.Raw[];
        nextPageToken?: ((CommonNextPageToken.Raw | undefined) | null | undefined) | null;
        totalSize?: CommonTotalSize.Raw | null;
    }
}
