// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentCardResponseSupportedInterfacesItemProtocolBinding: core.serialization.Schema<
    serializers.AgentCardResponseSupportedInterfacesItemProtocolBinding.Raw,
    Corti.AgentCardResponseSupportedInterfacesItemProtocolBinding
> = core.serialization.enum_(["JSONRPC", "HTTP+JSON"]);

export declare namespace AgentCardResponseSupportedInterfacesItemProtocolBinding {
    export type Raw = "JSONRPC" | "HTTP+JSON";
}
