// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentCardResponseCapabilities: core.serialization.ObjectSchema<
    serializers.AgentCardResponseCapabilities.Raw,
    Corti.AgentCardResponseCapabilities
> = core.serialization.object({
    streaming: core.serialization.boolean().optional(),
    pushNotifications: core.serialization.boolean().optional(),
});

export declare namespace AgentCardResponseCapabilities {
    export interface Raw {
        streaming?: boolean | null;
        pushNotifications?: boolean | null;
    }
}
