// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentsAgentCardSignature: core.serialization.ObjectSchema<
    serializers.AgentsAgentCardSignature.Raw,
    Corti.AgentsAgentCardSignature
> = core.serialization.object({
    protected: core.serialization.string(),
    signature: core.serialization.string(),
    header: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace AgentsAgentCardSignature {
    export interface Raw {
        protected: string;
        signature: string;
        header?: Record<string, unknown> | null;
    }
}
