// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { AgentsValidationError } from "./AgentsValidationError.js";

export const AgentsValidationErrorResponse: core.serialization.ObjectSchema<
    serializers.AgentsValidationErrorResponse.Raw,
    Corti.AgentsValidationErrorResponse
> = core.serialization
    .object({
        detail: core.serialization.list(AgentsValidationError).optional(),
    })
    .extend(core.serialization.lazyObject(() => serializers.AgentsErrorResponse));

export declare namespace AgentsValidationErrorResponse {
    export interface Raw extends serializers.AgentsErrorResponse.Raw {
        detail?: AgentsValidationError.Raw[] | null;
    }
}
