// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AgentsCreateExpertReferenceType } from "./AgentsCreateExpertReferenceType.js";

export const AgentsCreateExpertReference: core.serialization.ObjectSchema<
    serializers.AgentsCreateExpertReference.Raw,
    Corti.AgentsCreateExpertReference
> = core.serialization.object({
    type: AgentsCreateExpertReferenceType,
    id: core.serialization.string().optional(),
    name: core.serialization.string().optional(),
    systemPrompt: core.serialization.string().optional(),
});

export declare namespace AgentsCreateExpertReference {
    export interface Raw {
        type: AgentsCreateExpertReferenceType.Raw;
        id?: string | null;
        name?: string | null;
        systemPrompt?: string | null;
    }
}
