// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgenticRegistryIcon: core.serialization.ObjectSchema<
    serializers.AgenticRegistryIcon.Raw,
    Corti.AgenticRegistryIcon
> = core.serialization.object({
    src: core.serialization.string(),
    mimeType: core.serialization.string().optional(),
    sizes: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace AgenticRegistryIcon {
    export interface Raw {
        src: string;
        mimeType?: string | null;
        sizes?: string[] | null;
    }
}
