/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const AgentsExpertReference: core.serialization.ObjectSchema<
    serializers.AgentsExpertReference.Raw,
    Corti.AgentsExpertReference
> = core.serialization.object({
    type: core.serialization.stringLiteral("reference"),
    id: core.serialization.string(),
    name: core.serialization.string(),
    systemPrompt: core.serialization.string().optional(),
});

export declare namespace AgentsExpertReference {
    export interface Raw {
        type: "reference";
        id: string;
        name: string;
        systemPrompt?: string | null;
    }
}
