/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { AgentsValidationErrorErrorsItem } from "./AgentsValidationErrorErrorsItem.js";

export const AgentsValidationError: core.serialization.ObjectSchema<
    serializers.AgentsValidationError.Raw,
    Corti.AgentsValidationError
> = core.serialization.object({
    msg: core.serialization.string(),
    type: core.serialization.string(),
    reason: core.serialization.string(),
    howToFix: core.serialization.string(),
    errors: core.serialization.list(AgentsValidationErrorErrorsItem).optional(),
});

export declare namespace AgentsValidationError {
    export interface Raw {
        msg: string;
        type: string;
        reason: string;
        howToFix: string;
        errors?: AgentsValidationErrorErrorsItem.Raw[] | null;
    }
}
