/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { AgentsPart } from "./AgentsPart.js";

export const AgentsArtifact: core.serialization.ObjectSchema<serializers.AgentsArtifact.Raw, Corti.AgentsArtifact> =
    core.serialization.object({
        artifactId: core.serialization.string(),
        name: core.serialization.string().optional(),
        description: core.serialization.string().optional(),
        parts: core.serialization.list(AgentsPart),
        metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
        extensions: core.serialization.list(core.serialization.string()).optional(),
    });

export declare namespace AgentsArtifact {
    export interface Raw {
        artifactId: string;
        name?: string | null;
        description?: string | null;
        parts: AgentsPart.Raw[];
        metadata?: Record<string, unknown> | null;
        extensions?: string[] | null;
    }
}
