// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AgentsCreateMcpServerTransportType: core.serialization.Schema<
    serializers.AgentsCreateMcpServerTransportType.Raw,
    Corti.AgentsCreateMcpServerTransportType
> = core.serialization.enum_(["stdio", "streamable_http", "sse"]);

export declare namespace AgentsCreateMcpServerTransportType {
    export type Raw = "stdio" | "streamable_http" | "sse";
}
