// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AuthTokenRequestGrantType } from "./AuthTokenRequestGrantType.js";

export const AuthTokenRequest: core.serialization.ObjectSchema<
    serializers.AuthTokenRequest.Raw,
    Corti.AuthTokenRequest
> = core.serialization.object({
    clientId: core.serialization.property("client_id", core.serialization.string()),
    clientSecret: core.serialization.property("client_secret", core.serialization.string()),
    grantType: core.serialization.property("grant_type", AuthTokenRequestGrantType),
    scope: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace AuthTokenRequest {
    export interface Raw {
        client_id: string;
        client_secret: string;
        grant_type: AuthTokenRequestGrantType.Raw;
        scope?: string[] | null;
    }
}
