// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AuthTokenResponse: core.serialization.ObjectSchema<
    serializers.AuthTokenResponse.Raw,
    Corti.AuthTokenResponse
> = core.serialization.object({
    accessToken: core.serialization.property("access_token", core.serialization.string()),
    expiresIn: core.serialization.property("expires_in", core.serialization.number()),
    refreshExpiresIn: core.serialization.property("refresh_expires_in", core.serialization.number().optional()),
    refreshToken: core.serialization.property("refresh_token", core.serialization.string().optional()),
    tokenType: core.serialization.property("token_type", core.serialization.string()),
    idToken: core.serialization.property("id_token", core.serialization.string().optional()),
    notBeforePolicy: core.serialization.property("not-before-policy", core.serialization.number().optional()),
    scope: core.serialization.string().optional(),
    sessionState: core.serialization.property("session_state", core.serialization.string().optional()),
});

export declare namespace AuthTokenResponse {
    export interface Raw {
        access_token: string;
        expires_in: number;
        refresh_expires_in?: number | null;
        refresh_token?: string | null;
        token_type: string;
        id_token?: string | null;
        "not-before-policy"?: number | null;
        scope?: string | null;
        session_state?: string | null;
    }
}
