/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const CodesGeneralReadResponseEvidencesItem: core.serialization.ObjectSchema<
    serializers.CodesGeneralReadResponseEvidencesItem.Raw,
    Corti.CodesGeneralReadResponseEvidencesItem
> = core.serialization.object({
    contextIndex: core.serialization.number(),
    text: core.serialization.string(),
    start: core.serialization.number(),
    end: core.serialization.number(),
});

export declare namespace CodesGeneralReadResponseEvidencesItem {
    export interface Raw {
        contextIndex: number;
        text: string;
        start: number;
        end: number;
    }
}
