// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CodesGeneralReadResponseAlternativesItem } from "./CodesGeneralReadResponseAlternativesItem.js";
import { CodesGeneralReadResponseEvidencesItem } from "./CodesGeneralReadResponseEvidencesItem.js";
import { CommonCodingSystemEnum } from "./CommonCodingSystemEnum.js";

export const CodesGeneralReadResponse: core.serialization.ObjectSchema<
    serializers.CodesGeneralReadResponse.Raw,
    Corti.CodesGeneralReadResponse
> = core.serialization.object({
    system: CommonCodingSystemEnum,
    code: core.serialization.string(),
    display: core.serialization.string(),
    evidences: core.serialization.list(CodesGeneralReadResponseEvidencesItem).optional(),
    alternatives: core.serialization.list(CodesGeneralReadResponseAlternativesItem).optional(),
});

export declare namespace CodesGeneralReadResponse {
    export interface Raw {
        system: CommonCodingSystemEnum.Raw;
        code: string;
        display: string;
        evidences?: CodesGeneralReadResponseEvidencesItem.Raw[] | null;
        alternatives?: CodesGeneralReadResponseAlternativesItem.Raw[] | null;
    }
}
