/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const CommonDocumentIdContext: core.serialization.ObjectSchema<
    serializers.CommonDocumentIdContext.Raw,
    Corti.CommonDocumentIdContext
> = core.serialization.object({
    type: core.serialization.stringLiteral("documentId"),
    documentId: core.serialization.string(),
});

export declare namespace CommonDocumentIdContext {
    export interface Raw {
        type: "documentId";
        documentId: string;
    }
}
