// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CommonDocumentIdContextType: core.serialization.Schema<
    serializers.CommonDocumentIdContextType.Raw,
    Corti.CommonDocumentIdContextType
> = core.serialization.enum_(["documentId"]);

export declare namespace CommonDocumentIdContextType {
    export type Raw = "documentId";
}
