// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CommonCortiUsage: core.serialization.ObjectSchema<
    serializers.CommonCortiUsage.Raw,
    Corti.CommonCortiUsage
> = core.serialization.object({
    creditsConsumed: core.serialization.number(),
    inputTokens: core.serialization.number().optional(),
    outputTokens: core.serialization.number().optional(),
});

export declare namespace CommonCortiUsage {
    export interface Raw {
        creditsConsumed: number;
        inputTokens?: number | null;
        outputTokens?: number | null;
    }
}
