// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CommonA2AConnectorCreate } from "./CommonA2AConnectorCreate.js";
import { CommonAgentConnectorCreate } from "./CommonAgentConnectorCreate.js";
import { CommonMcpConnectorCreate } from "./CommonMcpConnectorCreate.js";
import { CommonRegistryConnectorCreate } from "./CommonRegistryConnectorCreate.js";
import { CommonSchemaConnectorCreate } from "./CommonSchemaConnectorCreate.js";

export const CommonConnectorCreateRequest: core.serialization.Schema<
    serializers.CommonConnectorCreateRequest.Raw,
    Corti.CommonConnectorCreateRequest
> = core.serialization.undiscriminatedUnion([
    CommonRegistryConnectorCreate,
    CommonMcpConnectorCreate,
    CommonAgentConnectorCreate,
    CommonA2AConnectorCreate,
    CommonSchemaConnectorCreate,
]);

export declare namespace CommonConnectorCreateRequest {
    export type Raw =
        | CommonRegistryConnectorCreate.Raw
        | CommonMcpConnectorCreate.Raw
        | CommonAgentConnectorCreate.Raw
        | CommonA2AConnectorCreate.Raw
        | CommonSchemaConnectorCreate.Raw;
}
