// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CommonErrorResponseErrorDetailsValidationErrorsItem } from "./CommonErrorResponseErrorDetailsValidationErrorsItem.js";

export const CommonErrorResponseErrorDetails: core.serialization.ObjectSchema<
    serializers.CommonErrorResponseErrorDetails.Raw,
    Corti.CommonErrorResponseErrorDetails
> = core.serialization
    .object({
        validationErrors: core.serialization.list(CommonErrorResponseErrorDetailsValidationErrorsItem).optional(),
    })
    .passthrough();

export declare namespace CommonErrorResponseErrorDetails {
    export interface Raw {
        validationErrors?: CommonErrorResponseErrorDetailsValidationErrorsItem.Raw[] | null;
        [key: string]: any;
    }
}
