/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { CommonTextContext } from "./CommonTextContext.js";
import { CommonDocumentIdContext } from "./CommonDocumentIdContext.js";

export const CommonAiContext: core.serialization.Schema<serializers.CommonAiContext.Raw, Corti.CommonAiContext> =
    core.serialization.undiscriminatedUnion([CommonTextContext, CommonDocumentIdContext]);

export declare namespace CommonAiContext {
    export type Raw = CommonTextContext.Raw | CommonDocumentIdContext.Raw;
}
