// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CommonConnectorIdValue } from "./CommonConnectorIdValue.js";

export const CommonRegistryConnectorProvisioned: core.serialization.ObjectSchema<
    serializers.CommonRegistryConnectorProvisioned.Raw,
    Corti.CommonRegistryConnectorProvisioned
> = core.serialization.object({
    type: core.serialization.stringLiteral("registry"),
    name: core.serialization.string(),
    config: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    id: CommonConnectorIdValue.optional(),
    enabled: core.serialization.boolean().optional(),
});

export declare namespace CommonRegistryConnectorProvisioned {
    export interface Raw {
        type: "registry";
        name: string;
        config?: Record<string, unknown> | null;
        id?: CommonConnectorIdValue.Raw | null;
        enabled?: boolean | null;
    }
}
