// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CommonNextPageToken } from "./CommonNextPageToken.js";
import { CommonTotalSize } from "./CommonTotalSize.js";
import { ContextsTraceItem } from "./ContextsTraceItem.js";

export const ContextsTraceResponse: core.serialization.ObjectSchema<
    serializers.ContextsTraceResponse.Raw,
    Corti.ContextsTraceResponse
> = core.serialization.object({
    traces: core.serialization.list(ContextsTraceItem),
    nextPageToken: CommonNextPageToken.optionalNullable(),
    totalSize: CommonTotalSize.optional(),
});

export declare namespace ContextsTraceResponse {
    export interface Raw {
        traces: ContextsTraceItem.Raw[];
        nextPageToken?: ((CommonNextPageToken.Raw | undefined) | null | undefined) | null;
        totalSize?: CommonTotalSize.Raw | null;
    }
}
