// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ContextsOpenInferenceSpan } from "./ContextsOpenInferenceSpan.js";
import { ContextsTraceItemTrace } from "./ContextsTraceItemTrace.js";

export const ContextsTraceItem: core.serialization.ObjectSchema<
    serializers.ContextsTraceItem.Raw,
    Corti.ContextsTraceItem
> = core.serialization.object({
    trace: ContextsTraceItemTrace,
    spans: core.serialization.list(ContextsOpenInferenceSpan),
});

export declare namespace ContextsTraceItem {
    export interface Raw {
        trace: ContextsTraceItemTrace.Raw;
        spans: ContextsOpenInferenceSpan.Raw[];
    }
}
