// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CreateTemplateBase } from "./CreateTemplateBase.js";
import { CreateTemplateFromScratchRequestGeneration } from "./CreateTemplateFromScratchRequestGeneration.js";

export const CreateTemplateFromScratchRequest: core.serialization.ObjectSchema<
    serializers.CreateTemplateFromScratchRequest.Raw,
    Corti.CreateTemplateFromScratchRequest
> = core.serialization
    .object({
        generation: CreateTemplateFromScratchRequestGeneration,
    })
    .extend(CreateTemplateBase);

export declare namespace CreateTemplateFromScratchRequest {
    export interface Raw extends CreateTemplateBase.Raw {
        generation: CreateTemplateFromScratchRequestGeneration.Raw;
    }
}
