// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TemplateInstructions } from "./TemplateInstructions.js";
import { TemplateVersionSectionRequest } from "./TemplateVersionSectionRequest.js";

export const CreateTemplateFromScratchRequestGeneration: core.serialization.ObjectSchema<
    serializers.CreateTemplateFromScratchRequestGeneration.Raw,
    Corti.CreateTemplateFromScratchRequestGeneration
> = core.serialization.object({
    instructions: TemplateInstructions,
    sections: core.serialization.list(TemplateVersionSectionRequest).optional(),
});

export declare namespace CreateTemplateFromScratchRequestGeneration {
    export interface Raw {
        instructions: TemplateInstructions.Raw;
        sections?: TemplateVersionSectionRequest.Raw[] | null;
    }
}
