// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { DocumentsCreateRequestWithTemplate } from "./DocumentsCreateRequestWithTemplate.js";
import { DocumentsCreateRequestWithTemplateKey } from "./DocumentsCreateRequestWithTemplateKey.js";

export const DocumentsCreateRequestBody: core.serialization.Schema<
    serializers.DocumentsCreateRequestBody.Raw,
    Corti.DocumentsCreateRequestBody
> = core.serialization.undiscriminatedUnion([
    DocumentsCreateRequestWithTemplateKey,
    DocumentsCreateRequestWithTemplate,
]);

export declare namespace DocumentsCreateRequestBody {
    export type Raw = DocumentsCreateRequestWithTemplateKey.Raw | DocumentsCreateRequestWithTemplate.Raw;
}
