/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { DocumentsContextWithTranscriptType } from "./DocumentsContextWithTranscriptType.js";
import { CommonTranscriptRequest } from "./CommonTranscriptRequest.js";

export const DocumentsContextWithTranscript: core.serialization.ObjectSchema<
    serializers.DocumentsContextWithTranscript.Raw,
    Corti.DocumentsContextWithTranscript
> = core.serialization.object({
    type: DocumentsContextWithTranscriptType,
    data: CommonTranscriptRequest,
});

export declare namespace DocumentsContextWithTranscript {
    export interface Raw {
        type: DocumentsContextWithTranscriptType.Raw;
        data: CommonTranscriptRequest.Raw;
    }
}
