/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { DocumentsTemplateWithSectionKeys } from "./DocumentsTemplateWithSectionKeys.js";

export const DocumentsTemplate: core.serialization.ObjectSchema<
    serializers.DocumentsTemplate.Raw,
    Corti.DocumentsTemplate
> = DocumentsTemplateWithSectionKeys;

export declare namespace DocumentsTemplate {
    export type Raw = DocumentsTemplateWithSectionKeys.Raw;
}
