/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const DocumentsContextWithStringType: core.serialization.Schema<
    serializers.DocumentsContextWithStringType.Raw,
    Corti.DocumentsContextWithStringType
> = core.serialization.enum_(["string"]);

export declare namespace DocumentsContextWithStringType {
    export type Raw = "string";
}
