// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EphemeralDocument: core.serialization.ObjectSchema<
    serializers.EphemeralDocument.Raw,
    Corti.EphemeralDocument
> = core.serialization.object({
    name: core.serialization.string(),
    templateId: core.serialization.string(),
    templateVersionId: core.serialization.string(),
    language: core.serialization.string(),
    stringDocument: core.serialization.record(core.serialization.string(), core.serialization.string()),
    structuredDocument: core.serialization
        .record(core.serialization.string(), core.serialization.unknown())
        .optionalNullable(),
});

export declare namespace EphemeralDocument {
    export interface Raw {
        name: string;
        templateId: string;
        templateVersionId: string;
        language: string;
        stringDocument: Record<string, string>;
        structuredDocument?: (Record<string, unknown> | null | undefined) | null;
    }
}
