/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import { CommonUsageInfo } from "./CommonUsageInfo.js";

export const FactsGenerateResponse: core.serialization.ObjectSchema<
    serializers.FactsGenerateResponse.Raw,
    Corti.FactsGenerateResponse
> = core.serialization.object({
    facts: core.serialization.unknown().optional(),
    outputLanguage: core.serialization.string().optional(),
    usageInfo: CommonUsageInfo.optional(),
});

export declare namespace FactsGenerateResponse {
    export interface Raw {
        facts?: unknown | null;
        outputLanguage?: string | null;
        usageInfo?: CommonUsageInfo.Raw | null;
    }
}
