/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const Fact: core.serialization.ObjectSchema<serializers.Fact.Raw, Corti.Fact> = core.serialization.object({
    group: core.serialization.string(),
    value: core.serialization.string(),
});

export declare namespace Fact {
    export interface Raw {
        group: string;
        value: string;
    }
}
