// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const GetTokenRequestPassword: core.serialization.ObjectSchema<
    serializers.GetTokenRequestPassword.Raw,
    Corti.GetTokenRequestPassword
> = core.serialization.object({
    grantType: core.serialization.property("grant_type", core.serialization.stringLiteral("password")),
    username: core.serialization.string(),
    password: core.serialization.string(),
    clientId: core.serialization.property("client_id", core.serialization.string()),
    clientSecret: core.serialization.property("client_secret", core.serialization.string().optional()),
});

export declare namespace GetTokenRequestPassword {
    export interface Raw {
        grant_type: "password";
        username: string;
        password: string;
        client_id: string;
        client_secret?: string | null;
    }
}
