// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GuidedDynamicRequest } from "./GuidedDynamicRequest.js";

export const GuidedDocumentByDynamicWithInteractionId: core.serialization.ObjectSchema<
    serializers.GuidedDocumentByDynamicWithInteractionId.Raw,
    Corti.GuidedDocumentByDynamicWithInteractionId
> = core.serialization.object({
    interactionId: core.serialization.string(),
    dynamicTemplate: GuidedDynamicRequest,
});

export declare namespace GuidedDocumentByDynamicWithInteractionId {
    export interface Raw {
        interactionId: string;
        dynamicTemplate: GuidedDynamicRequest.Raw;
    }
}
