// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { GuidedBoolNode } from "./GuidedBoolNode.js";
import { GuidedNumberNode } from "./GuidedNumberNode.js";
import { GuidedStringNode } from "./GuidedStringNode.js";

export const GuidedOutputSchema: core.serialization.Schema<
    serializers.GuidedOutputSchema.Raw,
    Corti.GuidedOutputSchema
> = core.serialization.undiscriminatedUnion([
    GuidedStringNode,
    GuidedNumberNode,
    GuidedBoolNode,
    core.serialization.lazyObject(() => serializers.GuidedObjectNode),
    core.serialization.lazyObject(() => serializers.GuidedArrayNode),
]);

export declare namespace GuidedOutputSchema {
    export type Raw =
        | GuidedStringNode.Raw
        | GuidedNumberNode.Raw
        | GuidedBoolNode.Raw
        | serializers.GuidedObjectNode.Raw
        | serializers.GuidedArrayNode.Raw;
}
