// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GuidedDocumentsGenerateBase } from "./GuidedDocumentsGenerateBase.js";
import { GuidedDynamicRequest } from "./GuidedDynamicRequest.js";

export const GuidedDocumentsGenerateByDynamic: core.serialization.ObjectSchema<
    serializers.GuidedDocumentsGenerateByDynamic.Raw,
    Corti.GuidedDocumentsGenerateByDynamic
> = core.serialization
    .object({
        dynamicTemplate: GuidedDynamicRequest,
    })
    .extend(GuidedDocumentsGenerateBase);

export declare namespace GuidedDocumentsGenerateByDynamic {
    export interface Raw extends GuidedDocumentsGenerateBase.Raw {
        dynamicTemplate: GuidedDynamicRequest.Raw;
    }
}
