// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GuidedTemplatesVersionSectionRequest } from "./GuidedTemplatesVersionSectionRequest.js";
import { TemplateInstructions } from "./TemplateInstructions.js";

export const GuidedTemplatesCreateFromScratchRequestGeneration: core.serialization.ObjectSchema<
    serializers.GuidedTemplatesCreateFromScratchRequestGeneration.Raw,
    Corti.GuidedTemplatesCreateFromScratchRequestGeneration
> = core.serialization.object({
    instructions: TemplateInstructions,
    sections: core.serialization.list(GuidedTemplatesVersionSectionRequest).optional(),
});

export declare namespace GuidedTemplatesCreateFromScratchRequestGeneration {
    export interface Raw {
        instructions: TemplateInstructions.Raw;
        sections?: GuidedTemplatesVersionSectionRequest.Raw[] | null;
    }
}
