// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { GuidedSectionInstructionsOverride } from "./GuidedSectionInstructionsOverride.js";

export const GuidedSectionOverrides: core.serialization.ObjectSchema<
    serializers.GuidedSectionOverrides.Raw,
    Corti.GuidedSectionOverrides
> = core.serialization.object({
    heading: core.serialization.string().optionalNullable(),
    instructions: GuidedSectionInstructionsOverride.optional(),
    outputSchema: core.serialization.lazy(() => serializers.OutputSchema).optional(),
});

export declare namespace GuidedSectionOverrides {
    export interface Raw {
        heading?: (string | null | undefined) | null;
        instructions?: GuidedSectionInstructionsOverride.Raw | null;
        outputSchema?: serializers.OutputSchema.Raw | null;
    }
}
