// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";

export const GuidedFieldDefinition: core.serialization.ObjectSchema<
    serializers.GuidedFieldDefinition.Raw,
    Corti.GuidedFieldDefinition
> = core.serialization.object({
    key: core.serialization.string(),
    description: core.serialization.string(),
    value: core.serialization.lazy(() => serializers.GuidedOutputSchema),
});

export declare namespace GuidedFieldDefinition {
    export interface Raw {
        key: string;
        description: string;
        value: serializers.GuidedOutputSchema.Raw;
    }
}
