// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const GuidedTemplateInstructions: core.serialization.ObjectSchema<
    serializers.GuidedTemplateInstructions.Raw,
    Corti.GuidedTemplateInstructions
> = core.serialization.object({
    prompt: core.serialization.string(),
});

export declare namespace GuidedTemplateInstructions {
    export interface Raw {
        prompt: string;
    }
}
