// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { DocumentsContext } from "./DocumentsContext.js";
import { GuidedDynamicRequest } from "./GuidedDynamicRequest.js";

export const GuidedDocumentByDynamic: core.serialization.ObjectSchema<
    serializers.GuidedDocumentByDynamic.Raw,
    Corti.GuidedDocumentByDynamic
> = core.serialization.object({
    context: DocumentsContext,
    dynamicTemplate: GuidedDynamicRequest,
});

export declare namespace GuidedDocumentByDynamic {
    export interface Raw {
        context: DocumentsContext.Raw;
        dynamicTemplate: GuidedDynamicRequest.Raw;
    }
}
