// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GuidedShallowTemplateGeneration } from "./GuidedShallowTemplateGeneration.js";

export const GuidedShallowTemplateVersionResponse: core.serialization.ObjectSchema<
    serializers.GuidedShallowTemplateVersionResponse.Raw,
    Corti.GuidedShallowTemplateVersionResponse
> = core.serialization.object({
    id: core.serialization.string(),
    versionNumber: core.serialization.number(),
    deletedAt: core.serialization.date().optionalNullable(),
    generation: GuidedShallowTemplateGeneration,
});

export declare namespace GuidedShallowTemplateVersionResponse {
    export interface Raw {
        id: string;
        versionNumber: number;
        deletedAt?: (string | null | undefined) | null;
        generation: GuidedShallowTemplateGeneration.Raw;
    }
}
