// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const GuidedTemplatesCreatePolicyRequestKind: core.serialization.Schema<
    serializers.GuidedTemplatesCreatePolicyRequestKind.Raw,
    Corti.GuidedTemplatesCreatePolicyRequestKind
> = core.serialization.enum_(["project", "customers"]);

export declare namespace GuidedTemplatesCreatePolicyRequestKind {
    export type Raw = "project" | "customers";
}
