// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const GuidedTemplatePolicyKind: core.serialization.Schema<
    serializers.GuidedTemplatePolicyKind.Raw,
    Corti.GuidedTemplatePolicyKind
> = core.serialization.enum_(["project", "customers"]);

export declare namespace GuidedTemplatePolicyKind {
    export type Raw = "project" | "customers";
}
