// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GuidedDocumentFactMinimal } from "./GuidedDocumentFactMinimal.js";

export const GuidedDocumentContextFacts: core.serialization.ObjectSchema<
    serializers.GuidedDocumentContextFacts.Raw,
    Corti.GuidedDocumentContextFacts
> = core.serialization.object({
    type: core.serialization.stringLiteral("facts"),
    facts: core.serialization.list(GuidedDocumentFactMinimal),
});

export declare namespace GuidedDocumentContextFacts {
    export interface Raw {
        type: "facts";
        facts: GuidedDocumentFactMinimal.Raw[];
    }
}
