// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GuidedSectionOverrides } from "./GuidedSectionOverrides.js";

export const GuidedAssemblySectionRef: core.serialization.ObjectSchema<
    serializers.GuidedAssemblySectionRef.Raw,
    Corti.GuidedAssemblySectionRef
> = core.serialization.object({
    sectionId: core.serialization.string(),
    sectionVersionId: core.serialization.string().optionalNullable(),
    overrides: GuidedSectionOverrides.optional(),
});

export declare namespace GuidedAssemblySectionRef {
    export interface Raw {
        sectionId: string;
        sectionVersionId?: (string | null | undefined) | null;
        overrides?: GuidedSectionOverrides.Raw | null;
    }
}
