// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GuidedTemplatesCreatePolicyRequestKind } from "./GuidedTemplatesCreatePolicyRequestKind.js";

export const GuidedTemplatesCreatePolicyRequest: core.serialization.ObjectSchema<
    serializers.GuidedTemplatesCreatePolicyRequest.Raw,
    Corti.GuidedTemplatesCreatePolicyRequest
> = core.serialization.object({
    kind: GuidedTemplatesCreatePolicyRequestKind,
    customerIds: core.serialization.list(core.serialization.string()).optionalNullable(),
});

export declare namespace GuidedTemplatesCreatePolicyRequest {
    export interface Raw {
        kind: GuidedTemplatesCreatePolicyRequestKind.Raw;
        customerIds?: (string[] | null | undefined) | null;
    }
}
