// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GuidedDocumentContext } from "./GuidedDocumentContext.js";
import { GuidedTemplateRef } from "./GuidedTemplateRef.js";

export const GuidedDocumentByTemplateRef: core.serialization.ObjectSchema<
    serializers.GuidedDocumentByTemplateRef.Raw,
    Corti.GuidedDocumentByTemplateRef
> = core.serialization.object({
    context: core.serialization.list(GuidedDocumentContext).optional(),
    interactionId: core.serialization.string().optional(),
    templateRef: GuidedTemplateRef,
});

export declare namespace GuidedDocumentByTemplateRef {
    export interface Raw {
        context?: GuidedDocumentContext.Raw[] | null;
        interactionId?: string | null;
        templateRef: GuidedTemplateRef.Raw;
    }
}
