// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { GuidedSectionListItem } from "./GuidedSectionListItem.js";
import { GuidedSectionVersion } from "./GuidedSectionVersion.js";

export const GuidedSection: core.serialization.ObjectSchema<serializers.GuidedSection.Raw, Corti.GuidedSection> =
    core.serialization
        .object({
            publishedVersion: GuidedSectionVersion.optional(),
        })
        .extend(GuidedSectionListItem);

export declare namespace GuidedSection {
    export interface Raw extends GuidedSectionListItem.Raw {
        publishedVersion?: GuidedSectionVersion.Raw | null;
    }
}
