// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const InteractionsEncounterPeriod: core.serialization.ObjectSchema<
    serializers.InteractionsEncounterPeriod.Raw,
    Corti.InteractionsEncounterPeriod
> = core.serialization.object({
    startedAt: core.serialization.date(),
    endedAt: core.serialization.date().optionalNullable(),
});

export declare namespace InteractionsEncounterPeriod {
    export interface Raw {
        startedAt: string;
        endedAt?: (string | null | undefined) | null;
    }
}
