// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ModelsModel } from "./ModelsModel.js";

export const ModelsListResponse: core.serialization.ObjectSchema<
    serializers.ModelsListResponse.Raw,
    Corti.ModelsListResponse
> = core.serialization.object({
    data: core.serialization.list(ModelsModel),
});

export declare namespace ModelsListResponse {
    export interface Raw {
        data: ModelsModel.Raw[];
    }
}
