// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { BoolNode } from "./BoolNode.js";
import { NumberNode } from "./NumberNode.js";
import { StringNode } from "./StringNode.js";

export const OutputSchema: core.serialization.Schema<serializers.OutputSchema.Raw, Corti.OutputSchema> =
    core.serialization.undiscriminatedUnion([
        StringNode,
        NumberNode,
        BoolNode,
        core.serialization.lazyObject(() => serializers.ObjectNode),
        core.serialization.lazyObject(() => serializers.ArrayNode),
    ]);

export declare namespace OutputSchema {
    export type Raw =
        | StringNode.Raw
        | NumberNode.Raw
        | BoolNode.Raw
        | serializers.ObjectNode.Raw
        | serializers.ArrayNode.Raw;
}
