// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import * as serializers from "../index.js";
import { SectionInstructionsPartial } from "./SectionInstructionsPartial.js";

export const SectionGenerationPartial: core.serialization.ObjectSchema<
    serializers.SectionGenerationPartial.Raw,
    Corti.SectionGenerationPartial
> = core.serialization.object({
    title: core.serialization.string().optional(),
    instructions: SectionInstructionsPartial.optional(),
    outputSchema: core.serialization.lazy(() => serializers.OutputSchema).optional(),
});

export declare namespace SectionGenerationPartial {
    export interface Raw {
        title?: string | null;
        instructions?: SectionInstructionsPartial.Raw | null;
        outputSchema?: serializers.OutputSchema.Raw | null;
    }
}
