/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const StreamConfigModeFactGenerationInterval: core.serialization.Schema<
    serializers.StreamConfigModeFactGenerationInterval.Raw,
    Corti.StreamConfigModeFactGenerationInterval
> = core.serialization.enum_(["fixed", "fast", "flexible"]);

export declare namespace StreamConfigModeFactGenerationInterval {
    export type Raw = "fixed" | "fast" | "flexible";
}
