// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TemplateVersionSectionRef: core.serialization.ObjectSchema<
    serializers.TemplateVersionSectionRef.Raw,
    Corti.TemplateVersionSectionRef
> = core.serialization.object({
    sectionId: core.serialization.string(),
    orderIndex: core.serialization.number(),
});

export declare namespace TemplateVersionSectionRef {
    export interface Raw {
        sectionId: string;
        orderIndex: number;
    }
}
