// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TemplateSource: core.serialization.Schema<serializers.TemplateSource.Raw, Corti.TemplateSource> =
    core.serialization.enum_(["user", "corti"]);

export declare namespace TemplateSource {
    export type Raw = "user" | "corti";
}
