// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TemplateVersionSectionRequest: core.serialization.ObjectSchema<
    serializers.TemplateVersionSectionRequest.Raw,
    Corti.TemplateVersionSectionRequest
> = core.serialization.object({
    sectionId: core.serialization.string(),
    pinnedVersionId: core.serialization.string().optionalNullable(),
    orderIndex: core.serialization.number().optional(),
});

export declare namespace TemplateVersionSectionRequest {
    export interface Raw {
        sectionId: string;
        pinnedVersionId?: (string | null | undefined) | null;
        orderIndex?: number | null;
    }
}
