// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Label } from "./Label.js";
import { TemplatePolicy } from "./TemplatePolicy.js";
import { TemplateSource } from "./TemplateSource.js";
import { TemplateVersion } from "./TemplateVersion.js";

export const Template: core.serialization.ObjectSchema<serializers.Template.Raw, Corti.Template> =
    core.serialization.object({
        id: core.serialization.string(),
        inheritedFromId: core.serialization.string().optionalNullable(),
        autoGenerated: core.serialization.boolean().optional(),
        source: TemplateSource.optional(),
        name: core.serialization.string(),
        description: core.serialization.string().optional(),
        languages: core.serialization.list(core.serialization.string()),
        regions: core.serialization.list(core.serialization.string()),
        specialties: core.serialization.list(core.serialization.string()),
        labels: core.serialization.list(Label),
        policies: core.serialization.list(TemplatePolicy).optional(),
        publishedVersion: TemplateVersion.optional(),
        createdAt: core.serialization.date(),
        updatedAt: core.serialization.date(),
        deletedAt: core.serialization.date().optionalNullable(),
    });

export declare namespace Template {
    export interface Raw {
        id: string;
        inheritedFromId?: (string | null | undefined) | null;
        autoGenerated?: boolean | null;
        source?: TemplateSource.Raw | null;
        name: string;
        description?: string | null;
        languages: string[];
        regions: string[];
        specialties: string[];
        labels: Label.Raw[];
        policies?: TemplatePolicy.Raw[] | null;
        publishedVersion?: TemplateVersion.Raw | null;
        createdAt: string;
        updatedAt: string;
        deletedAt?: (string | null | undefined) | null;
    }
}
