// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TemplatesDocumentationModeEnum: core.serialization.Schema<
    serializers.TemplatesDocumentationModeEnum.Raw,
    Corti.TemplatesDocumentationModeEnum
> = core.serialization.enum_(["global_sequential", "routed_parallel"]);

export declare namespace TemplatesDocumentationModeEnum {
    export type Raw = "global_sequential" | "routed_parallel";
}
