// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TemplateGeneration } from "./TemplateGeneration.js";

export const TemplateVersion: core.serialization.ObjectSchema<serializers.TemplateVersion.Raw, Corti.TemplateVersion> =
    core.serialization.object({
        id: core.serialization.string(),
        versionNumber: core.serialization.number(),
        generation: TemplateGeneration,
    });

export declare namespace TemplateVersion {
    export interface Raw {
        id: string;
        versionNumber: number;
        generation: TemplateGeneration.Raw;
    }
}
