/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const TemplatesSectionTranslation: core.serialization.ObjectSchema<
    serializers.TemplatesSectionTranslation.Raw,
    Corti.TemplatesSectionTranslation
> = core.serialization.object({
    languageId: core.serialization.string(),
    name: core.serialization.string().optionalNullable(),
    description: core.serialization.string().optionalNullable(),
});

export declare namespace TemplatesSectionTranslation {
    export interface Raw {
        languageId: string;
        name?: (string | null) | null;
        description?: (string | null) | null;
    }
}
