// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TranscribeConfigStatusMessageType: core.serialization.Schema<
    serializers.TranscribeConfigStatusMessageType.Raw,
    Corti.TranscribeConfigStatusMessageType
> = core.serialization.enum_(["CONFIG_ACCEPTED", "CONFIG_DENIED", "CONFIG_TIMEOUT"]);

export declare namespace TranscribeConfigStatusMessageType {
    export type Raw = "CONFIG_ACCEPTED" | "CONFIG_DENIED" | "CONFIG_TIMEOUT";
}
