// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TranscribeCommandRemove: core.serialization.ObjectSchema<
    serializers.TranscribeCommandRemove.Raw,
    Corti.TranscribeCommandRemove
> = core.serialization.object({
    id: core.serialization.string(),
});

export declare namespace TranscribeCommandRemove {
    export interface Raw {
        id: string;
    }
}
