/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const TranscribeFormattingDates: core.serialization.Schema<
    serializers.TranscribeFormattingDates.Raw,
    Corti.TranscribeFormattingDates
> = core.serialization.enum_(["as_dictated", "eu_slash", "iso_compact", "long_text", "us_slash"]);

export declare namespace TranscribeFormattingDates {
    export type Raw = "as_dictated" | "eu_slash" | "iso_compact" | "long_text" | "us_slash";
}
