// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TranscribeFormattingNumericRanges: core.serialization.Schema<
    serializers.TranscribeFormattingNumericRanges.Raw,
    Corti.TranscribeFormattingNumericRanges
> = core.serialization.enum_(["numerals", "as_dictated"]);

export declare namespace TranscribeFormattingNumericRanges {
    export type Raw = "numerals" | "as_dictated";
}
