// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CommonTranscriptResponse } from "./CommonTranscriptResponse.js";
import { TranscriptsMetadata } from "./TranscriptsMetadata.js";

export const TranscriptsData: core.serialization.ObjectSchema<serializers.TranscriptsData.Raw, Corti.TranscriptsData> =
    core.serialization.object({
        metadata: TranscriptsMetadata,
        transcripts: core.serialization.list(CommonTranscriptResponse),
    });

export declare namespace TranscriptsData {
    export interface Raw {
        metadata: TranscriptsMetadata.Raw;
        transcripts: CommonTranscriptResponse.Raw[];
    }
}
