// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TranscribeAudioEventsConfig: core.serialization.ObjectSchema<
    serializers.TranscribeAudioEventsConfig.Raw,
    Corti.TranscribeAudioEventsConfig
> = core.serialization.object({
    enabled: core.serialization.boolean(),
});

export declare namespace TranscribeAudioEventsConfig {
    export interface Raw {
        enabled: boolean;
    }
}
