// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TranscribeConfigReplacementsItem: core.serialization.ObjectSchema<
    serializers.TranscribeConfigReplacementsItem.Raw,
    Corti.TranscribeConfigReplacementsItem
> = core.serialization.object({
    find: core.serialization.string(),
    replace: core.serialization.string(),
});

export declare namespace TranscribeConfigReplacementsItem {
    export interface Raw {
        find: string;
        replace: string;
    }
}
