// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TranscribeFlushMessageType } from "./TranscribeFlushMessageType.js";

export const TranscribeFlushMessage: core.serialization.ObjectSchema<
    serializers.TranscribeFlushMessage.Raw,
    Corti.TranscribeFlushMessage
> = core.serialization.object({
    type: TranscribeFlushMessageType,
});

export declare namespace TranscribeFlushMessage {
    export interface Raw {
        type: TranscribeFlushMessageType.Raw;
    }
}
