/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";

export const TranscribeFlushedMessage: core.serialization.ObjectSchema<
    serializers.TranscribeFlushedMessage.Raw,
    Corti.TranscribeFlushedMessage
> = core.serialization.object({
    type: core.serialization.stringLiteral("flushed"),
});

export declare namespace TranscribeFlushedMessage {
    export interface Raw {
        type: "flushed";
    }
}
