// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Uuid: core.serialization.Schema<serializers.Uuid.Raw, Corti.Uuid> = core.serialization.string();

export declare namespace Uuid {
    export type Raw = string;
}
