/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../../../index.js";

export interface AgentsMessageStreamResponse {
    message?: Corti.AgentsMessage;
    task?: Corti.AgentsTask;
    statusUpdate?: Corti.AgentsTaskStatusUpdateEvent;
    artifactUpdate?: Corti.AgentsTaskArtifactUpdateEvent;
}
