// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../index.js";

export interface AgentsTaskStatus {
    /** The current state of the task. */
    state: Corti.agents.AgentsTaskStatusState;
    /** Additional message or details about the task status. */
    message?: Corti.agents.AgentsMessage;
    /** The timestamp when this status was recorded. */
    timestamp?: Date;
}
