// This file was auto-generated by Fern from our API Definition.

import * as Corti from "../../../../src/api/index";
import { CortiClient } from "../../../../src/Client";
import { mockServerPool } from "../../../mock-server/MockServerPool";
import { mockOAuth } from "../../mockAuth";

describe("PoliciesClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = [
            {
                id: "id",
                kind: "project",
                customerIds: ["customerIds"],
                templateId: "templateId",
                createdBy: "createdBy",
                createdAt: "2024-01-15T09:30:00Z",
                updatedAt: "2024-01-15T09:30:00Z",
            },
        ];

        server
            .mockEndpoint()
            .get("/documents/templates/templateID/policies/")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.documents.templates.policies.list("templateID");
        expect(response).toEqual([
            {
                id: "id",
                kind: "project",
                customerIds: ["customerIds"],
                templateId: "templateId",
                createdBy: "createdBy",
                createdAt: new Date("2024-01-15T09:30:00.000Z"),
                updatedAt: new Date("2024-01-15T09:30:00.000Z"),
            },
        ]);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/documents/templates/templateID/policies/")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.documents.templates.policies.list("templateID");
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = [{ kind: "project" }];
        const rawResponseBody = [
            {
                id: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                kind: "project",
                templateId: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                createdBy: "1a2b3c4d-5e6f-7890-abcd-ef1234567890",
                createdAt: "2025-06-01T12:00:00Z",
                updatedAt: "2025-06-01T12:00:00Z",
            },
        ];

        server
            .mockEndpoint()
            .post("/documents/templates/templateID/policies/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.documents.templates.policies.create("templateID", [
            {
                kind: "project",
            },
        ]);
        expect(response).toEqual([
            {
                id: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                kind: "project",
                templateId: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                createdBy: "1a2b3c4d-5e6f-7890-abcd-ef1234567890",
                createdAt: new Date("2025-06-01T12:00:00.000Z"),
                updatedAt: new Date("2025-06-01T12:00:00.000Z"),
            },
        ]);
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = [{ kind: "customers", customerIds: ["customer-tenant-a", "customer-tenant-b"] }];
        const rawResponseBody = [
            {
                id: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                kind: "project",
                templateId: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                createdBy: "1a2b3c4d-5e6f-7890-abcd-ef1234567890",
                createdAt: "2025-06-01T12:00:00Z",
                updatedAt: "2025-06-01T12:00:00Z",
            },
        ];

        server
            .mockEndpoint()
            .post("/documents/templates/templateID/policies/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.documents.templates.policies.create("templateID", [
            {
                kind: "customers",
                customerIds: ["customer-tenant-a", "customer-tenant-b"],
            },
        ]);
        expect(response).toEqual([
            {
                id: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                kind: "project",
                templateId: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                createdBy: "1a2b3c4d-5e6f-7890-abcd-ef1234567890",
                createdAt: new Date("2025-06-01T12:00:00.000Z"),
                updatedAt: new Date("2025-06-01T12:00:00.000Z"),
            },
        ]);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = [{ kind: "project" }];
        const rawResponseBody = [
            {
                id: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                kind: "project",
                templateId: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                createdBy: "1a2b3c4d-5e6f-7890-abcd-ef1234567890",
                createdAt: "2025-06-01T12:00:00Z",
                updatedAt: "2025-06-01T12:00:00Z",
            },
        ];

        server
            .mockEndpoint()
            .post("/documents/templates/templateID/policies/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.documents.templates.policies.create("templateID", [
            {
                kind: "project",
            },
        ]);
        expect(response).toEqual([
            {
                id: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                kind: "project",
                templateId: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                createdBy: "1a2b3c4d-5e6f-7890-abcd-ef1234567890",
                createdAt: new Date("2025-06-01T12:00:00.000Z"),
                updatedAt: new Date("2025-06-01T12:00:00.000Z"),
            },
        ]);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = [{ kind: "project" }];
        const rawResponseBody = [
            {
                id: "550e8400-e29b-41d4-a716-446655440000",
                kind: "customers",
                customerIds: ["customer-tenant-a", "customer-tenant-b"],
                templateId: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                createdBy: "1a2b3c4d-5e6f-7890-abcd-ef1234567890",
                createdAt: "2025-06-01T12:00:00Z",
                updatedAt: "2025-06-01T12:00:00Z",
            },
        ];

        server
            .mockEndpoint()
            .post("/documents/templates/templateID/policies/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.documents.templates.policies.create("templateID", [
            {
                kind: "project",
            },
        ]);
        expect(response).toEqual([
            {
                id: "550e8400-e29b-41d4-a716-446655440000",
                kind: "customers",
                customerIds: ["customer-tenant-a", "customer-tenant-b"],
                templateId: "7c9e6679-7425-40de-944b-e07fc1f90ae7",
                createdBy: "1a2b3c4d-5e6f-7890-abcd-ef1234567890",
                createdAt: new Date("2025-06-01T12:00:00.000Z"),
                updatedAt: new Date("2025-06-01T12:00:00.000Z"),
            },
        ]);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = [{ kind: "project" }, { kind: "project" }];
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/documents/templates/templateID/policies/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.documents.templates.policies.create("templateID", [
                {
                    kind: "project",
                },
                {
                    kind: "project",
                },
            ]);
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = [{ kind: "project" }, { kind: "project" }];
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/documents/templates/templateID/policies/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.documents.templates.policies.create("templateID", [
                {
                    kind: "project",
                },
                {
                    kind: "project",
                },
            ]);
        }).rejects.toThrow(Corti.NotFoundError);
    });
});
