// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../../api/index.js";
import * as core from "../../../../../../core/index.js";
import type * as serializers from "../../../../../index.js";

export const A2AjsonrpcRequestMethod: core.serialization.Schema<
    serializers.agents.A2AjsonrpcRequestMethod.Raw,
    Corti.agents.A2AjsonrpcRequestMethod
> = core.serialization.enum_([
    "SendMessage",
    "SendStreamingMessage",
    "GetTask",
    "ListTasks",
    "CancelTask",
    "SubscribeToTask",
]);

export declare namespace A2AjsonrpcRequestMethod {
    export type Raw =
        | "SendMessage"
        | "SendStreamingMessage"
        | "GetTask"
        | "ListTasks"
        | "CancelTask"
        | "SubscribeToTask";
}
