// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../../../../../../../api/index.js";
import * as core from "../../../../../../../../../../../core/index.js";
import type * as serializers from "../../../../../../../../../../index.js";
import { AgenticFeedbackLabel } from "../../../../../../../../../../types/AgenticFeedbackLabel.js";
import { AgenticFeedbackMetadata } from "../../../../../../../../../../types/AgenticFeedbackMetadata.js";
import { AgenticFeedbackRating } from "../../../../../../../../../../types/AgenticFeedbackRating.js";
import { AgenticFeedbackTarget } from "../../../../../../../../../../types/AgenticFeedbackTarget.js";

export const AgenticFeedbackCreateRequest: core.serialization.Schema<
    serializers.agentic.contexts.tasks.AgenticFeedbackCreateRequest.Raw,
    Corti.agentic.contexts.tasks.AgenticFeedbackCreateRequest
> = core.serialization.object({
    rating: AgenticFeedbackRating,
    labels: core.serialization.list(AgenticFeedbackLabel).optional(),
    reason: core.serialization.string().optional(),
    target: AgenticFeedbackTarget.optional(),
    metadata: AgenticFeedbackMetadata.optional(),
});

export declare namespace AgenticFeedbackCreateRequest {
    export interface Raw {
        rating: AgenticFeedbackRating.Raw;
        labels?: AgenticFeedbackLabel.Raw[] | null;
        reason?: string | null;
        target?: AgenticFeedbackTarget.Raw | null;
        metadata?: AgenticFeedbackMetadata.Raw | null;
    }
}
