// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const TranscriptsCreateRequestReplacementsItem: core.serialization.ObjectSchema<
    serializers.TranscriptsCreateRequestReplacementsItem.Raw,
    Corti.TranscriptsCreateRequestReplacementsItem
> = core.serialization.object({
    find: core.serialization.string(),
    replace: core.serialization.string(),
});

export declare namespace TranscriptsCreateRequestReplacementsItem {
    export interface Raw {
        find: string;
        replace: string;
    }
}
