// This file was auto-generated by Fern from our API Definition.

import * as Corti from "../../src/api/index";
import { CortiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";
import { mockOAuth } from "./mockAuth";

describe("AgenticClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = {
            agents: [
                {
                    id: "agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40",
                    name: "coder",
                    description: "description",
                    systemPrompt: "systemPrompt",
                    model: "corti-default",
                    visibility: "private",
                    lifecycle: "persistent",
                    connectors: [
                        {
                            id: "con.0192f4c8-7baf-7083-a46f-81d2bd70cf95",
                            type: "registry",
                            name: "@dedalus/coding-expert",
                        },
                    ],
                    labels: { key: "value" },
                    createdAt: "2026-05-19T12:00:00Z",
                    updatedAt: "2026-05-19T12:00:00Z",
                    createdBy: "usr.0192f4c8-8bc0-7194-8570-92e3ce81d0a6",
                },
            ],
            nextPageToken: "nextPageToken",
            totalSize: 42,
        };

        server.mockEndpoint().get("/v2/agentic/agents").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agentic.list({
            label: ["team=coding"],
            q: "coder",
        });
        expect(response).toEqual({
            agents: [
                {
                    id: "agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40",
                    name: "coder",
                    description: "description",
                    systemPrompt: "systemPrompt",
                    model: "corti-default",
                    visibility: "private",
                    lifecycle: "persistent",
                    connectors: [
                        {
                            id: "con.0192f4c8-7baf-7083-a46f-81d2bd70cf95",
                            type: "registry",
                            name: "@dedalus/coding-expert",
                        },
                    ],
                    labels: {
                        key: "value",
                    },
                    createdAt: new Date("2026-05-19T12:00:00.000Z"),
                    updatedAt: new Date("2026-05-19T12:00:00.000Z"),
                    createdBy: "usr.0192f4c8-8bc0-7194-8570-92e3ce81d0a6",
                },
            ],
            nextPageToken: "nextPageToken",
            totalSize: 42,
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v2/agentic/agents").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agentic.list();
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server.mockEndpoint().get("/v2/agentic/agents").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agentic.list();
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            name: "coder",
            description: "Returns ICD-10 codes for a clinical encounter.",
            systemPrompt: "Respond with only the ICD-10 code.",
            model: "corti-default",
            visibility: "private",
            lifecycle: "persistent",
            connectors: [
                { type: "registry", name: "@dedalus/coding-expert" },
                {
                    type: "mcp",
                    name: "policybot",
                    url: "https://mcp.example.com",
                    auth: {
                        type: "oauth2",
                        scope: "read:policies",
                        redirectUrl: "https://app.corti.ai/oauth/callback",
                    },
                },
                {
                    type: "schema",
                    name: "submit_code",
                    description: "Submit the final ICD-10 code for the encounter along with a confidence score.",
                    schema: {
                        type: "object",
                        properties: {
                            code: { type: "string", description: "The selected ICD-10 code." },
                            confidence: { type: "number", minimum: 0, maximum: 1 },
                        },
                        required: ["code"],
                    },
                    transition: "complete",
                },
            ],
            labels: { team: "coding", env: "prod" },
        };
        const rawResponseBody = {
            id: "agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40",
            name: "coder",
            description: "Returns ICD-10 codes for a clinical encounter.",
            systemPrompt: "Respond with only the ICD-10 code.",
            model: "corti-default",
            visibility: "private",
            lifecycle: "persistent",
            connectors: [
                {
                    id: "con.0192f4c8-7baf-7083-a46f-81d2bd70cf95",
                    type: "registry",
                    enabled: true,
                    name: "@dedalus/coding-expert",
                    config: { key: "value" },
                },
            ],
            labels: { team: "coding", env: "prod" },
            createdAt: "2026-05-19T12:00:00Z",
            updatedAt: "2026-05-19T12:00:00Z",
            createdBy: "usr.0192f4c8-8bc0-7194-8570-92e3ce81d0a6",
        };

        server
            .mockEndpoint()
            .post("/v2/agentic/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentic.create({
            name: "coder",
            description: "Returns ICD-10 codes for a clinical encounter.",
            systemPrompt: "Respond with only the ICD-10 code.",
            model: "corti-default",
            visibility: "private",
            lifecycle: "persistent",
            connectors: [
                {
                    type: "registry",
                    name: "@dedalus/coding-expert",
                },
                {
                    type: "mcp",
                    name: "policybot",
                    url: "https://mcp.example.com",
                    auth: {
                        type: "oauth2",
                        scope: "read:policies",
                        redirectUrl: "https://app.corti.ai/oauth/callback",
                    },
                },
                {
                    type: "schema",
                    name: "submit_code",
                    description: "Submit the final ICD-10 code for the encounter along with a confidence score.",
                    schema: {
                        type: "object",
                        properties: {
                            code: {
                                type: "string",
                                description: "The selected ICD-10 code.",
                            },
                            confidence: {
                                type: "number",
                                minimum: 0,
                                maximum: 1,
                            },
                        },
                        required: ["code"],
                    },
                    transition: "complete",
                },
            ],
            labels: {
                team: "coding",
                env: "prod",
            },
        });
        expect(response).toEqual({
            id: "agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40",
            name: "coder",
            description: "Returns ICD-10 codes for a clinical encounter.",
            systemPrompt: "Respond with only the ICD-10 code.",
            model: "corti-default",
            visibility: "private",
            lifecycle: "persistent",
            connectors: [
                {
                    id: "con.0192f4c8-7baf-7083-a46f-81d2bd70cf95",
                    type: "registry",
                    enabled: true,
                    name: "@dedalus/coding-expert",
                    config: {
                        key: "value",
                    },
                },
            ],
            labels: {
                team: "coding",
                env: "prod",
            },
            createdAt: new Date("2026-05-19T12:00:00.000Z"),
            updatedAt: new Date("2026-05-19T12:00:00.000Z"),
            createdBy: "usr.0192f4c8-8bc0-7194-8570-92e3ce81d0a6",
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v2/agentic/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.create({
                name: "x",
            });
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v2/agentic/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.create({
                name: "x",
            });
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("create (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v2/agentic/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.create({
                name: "x",
            });
        }).rejects.toThrow(Corti.ForbiddenError);
    });

    test("create (5)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v2/agentic/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(409)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.create({
                name: "x",
            });
        }).rejects.toThrow(Corti.ConflictError);
    });

    test("create (6)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { name: "x" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v2/agentic/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.create({
                name: "x",
            });
        }).rejects.toThrow(Corti.UnprocessableEntityError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = {
            id: "agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40",
            name: "coder",
            description: "Returns ICD-10 codes for a clinical encounter.",
            systemPrompt: "Respond with only the ICD-10 code.",
            model: "corti-default",
            visibility: "private",
            lifecycle: "persistent",
            connectors: [
                {
                    id: "con.0192f4c8-7baf-7083-a46f-81d2bd70cf95",
                    type: "registry",
                    enabled: true,
                    name: "@dedalus/coding-expert",
                    config: { key: "value" },
                },
            ],
            labels: { team: "coding", env: "prod" },
            createdAt: "2026-05-19T12:00:00Z",
            updatedAt: "2026-05-19T12:00:00Z",
            createdBy: "usr.0192f4c8-8bc0-7194-8570-92e3ce81d0a6",
        };

        server
            .mockEndpoint()
            .get("/v2/agentic/agents/agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentic.get("agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40");
        expect(response).toEqual({
            id: "agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40",
            name: "coder",
            description: "Returns ICD-10 codes for a clinical encounter.",
            systemPrompt: "Respond with only the ICD-10 code.",
            model: "corti-default",
            visibility: "private",
            lifecycle: "persistent",
            connectors: [
                {
                    id: "con.0192f4c8-7baf-7083-a46f-81d2bd70cf95",
                    type: "registry",
                    enabled: true,
                    name: "@dedalus/coding-expert",
                    config: {
                        key: "value",
                    },
                },
            ],
            labels: {
                team: "coding",
                env: "prod",
            },
            createdAt: new Date("2026-05-19T12:00:00.000Z"),
            updatedAt: new Date("2026-05-19T12:00:00.000Z"),
            createdBy: "usr.0192f4c8-8bc0-7194-8570-92e3ce81d0a6",
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/agentic/agents/agentId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.get("agentId");
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("get (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/agentic/agents/agentId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.get("agentId");
        }).rejects.toThrow(Corti.ForbiddenError);
    });

    test("get (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/agentic/agents/agentId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.get("agentId");
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        server
            .mockEndpoint()
            .delete("/v2/agentic/agents/agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.agentic.delete("agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40");
        expect(response).toEqual(undefined);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v2/agentic/agents/agentId")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.delete("agentId");
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v2/agentic/agents/agentId")
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.delete("agentId");
        }).rejects.toThrow(Corti.ForbiddenError);
    });

    test("delete (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v2/agentic/agents/agentId")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.delete("agentId");
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { name: "coder-v2", connectors: [{ type: "registry", name: "@dedalus/coding-expert" }] };
        const rawResponseBody = {
            id: "agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40",
            name: "coder",
            description: "Returns ICD-10 codes for a clinical encounter.",
            systemPrompt: "Respond with only the ICD-10 code.",
            model: "corti-default",
            visibility: "private",
            lifecycle: "persistent",
            connectors: [
                {
                    id: "con.0192f4c8-7baf-7083-a46f-81d2bd70cf95",
                    type: "registry",
                    enabled: true,
                    name: "@dedalus/coding-expert",
                    config: { key: "value" },
                },
            ],
            labels: { team: "coding", env: "prod" },
            createdAt: "2026-05-19T12:00:00Z",
            updatedAt: "2026-05-19T12:00:00Z",
            createdBy: "usr.0192f4c8-8bc0-7194-8570-92e3ce81d0a6",
        };

        server
            .mockEndpoint()
            .patch("/v2/agentic/agents/agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentic.update("agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40", {
            name: "coder-v2",
            connectors: [
                {
                    type: "registry",
                    name: "@dedalus/coding-expert",
                },
            ],
        });
        expect(response).toEqual({
            id: "agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40",
            name: "coder",
            description: "Returns ICD-10 codes for a clinical encounter.",
            systemPrompt: "Respond with only the ICD-10 code.",
            model: "corti-default",
            visibility: "private",
            lifecycle: "persistent",
            connectors: [
                {
                    id: "con.0192f4c8-7baf-7083-a46f-81d2bd70cf95",
                    type: "registry",
                    enabled: true,
                    name: "@dedalus/coding-expert",
                    config: {
                        key: "value",
                    },
                },
            ],
            labels: {
                team: "coding",
                env: "prod",
            },
            createdAt: new Date("2026-05-19T12:00:00.000Z"),
            updatedAt: new Date("2026-05-19T12:00:00.000Z"),
            createdBy: "usr.0192f4c8-8bc0-7194-8570-92e3ce81d0a6",
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v2/agentic/agents/agentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.update("agentId");
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("update (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v2/agentic/agents/agentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.update("agentId");
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("update (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v2/agentic/agents/agentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(403)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.update("agentId");
        }).rejects.toThrow(Corti.ForbiddenError);
    });

    test("update (5)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v2/agentic/agents/agentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.update("agentId");
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("update (6)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .patch("/v2/agentic/agents/agentId")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(422)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.update("agentId");
        }).rejects.toThrow(Corti.UnprocessableEntityError);
    });

    test("getCard (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = {
            name: "coder",
            description: "Returns ICD-10 codes for a clinical encounter.",
            documentationUrl: "documentationUrl",
            iconUrl: "iconUrl",
            version: "0.1.0",
            capabilities: { streaming: true, pushNotifications: false },
            defaultInputModes: ["text/plain"],
            defaultOutputModes: ["text/plain"],
            provider: { organization: "Corti", url: "https://corti.ai" },
            securityRequirements: [{ key: "value" }],
            securitySchemes: { key: "value" },
            signatures: [{ protected: "protected", header: { key: "value" }, signature: "signature" }],
            skills: [
                {
                    id: "con.0192f4c8-7baf-7083-a46f-81d2bd70cf95",
                    name: "coding-expert",
                    description: "ICD-10 coding.",
                    tags: ["expert"],
                },
            ],
            supportedInterfaces: [
                {
                    protocolBinding: "JSONRPC",
                    protocolVersion: "1.0",
                    url: "https://api.eu.corti.app/v2/agentic/agents/agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40/a2a",
                },
                {
                    protocolBinding: "HTTP+JSON",
                    protocolVersion: "1.0",
                    url: "https://api.eu.corti.app/v2/agentic/agents/agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40/a2a",
                },
            ],
        };

        server
            .mockEndpoint()
            .get("/v2/agentic/agents/agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40/.well-known/agent-card.json")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentic.getCard("agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40");
        expect(response).toEqual({
            name: "coder",
            description: "Returns ICD-10 codes for a clinical encounter.",
            documentationUrl: "documentationUrl",
            iconUrl: "iconUrl",
            version: "0.1.0",
            capabilities: {
                streaming: true,
                pushNotifications: false,
            },
            defaultInputModes: ["text/plain"],
            defaultOutputModes: ["text/plain"],
            provider: {
                organization: "Corti",
                url: "https://corti.ai",
            },
            securityRequirements: [
                {
                    key: "value",
                },
            ],
            securitySchemes: {
                key: "value",
            },
            signatures: [
                {
                    protected: "protected",
                    header: {
                        key: "value",
                    },
                    signature: "signature",
                },
            ],
            skills: [
                {
                    id: "con.0192f4c8-7baf-7083-a46f-81d2bd70cf95",
                    name: "coding-expert",
                    description: "ICD-10 coding.",
                    tags: ["expert"],
                },
            ],
            supportedInterfaces: [
                {
                    protocolBinding: "JSONRPC",
                    protocolVersion: "1.0",
                    url: "https://api.eu.corti.app/v2/agentic/agents/agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40/a2a",
                },
                {
                    protocolBinding: "HTTP+JSON",
                    protocolVersion: "1.0",
                    url: "https://api.eu.corti.app/v2/agentic/agents/agt.0192f4c8-2c5a-7b3e-9f1a-3c8d6e2b7a40/a2a",
                },
            ],
        });
    });

    test("getCard (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/agentic/agents/agentId/.well-known/agent-card.json")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.getCard("agentId");
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("getCard (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/agentic/agents/agentId/.well-known/agent-card.json")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agentic.getCard("agentId");
        }).rejects.toThrow(Corti.NotFoundError);
    });
});
