// This file was auto-generated by Fern from our API Definition.

import * as Corti from "../../src/api/index";
import { CortiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AgentsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CortiClient({
            maxRetries: 0,
            token: "test",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = [
            {
                id: "id",
                name: "name",
                description: "description",
                systemPrompt: "systemPrompt",
                experts: [
                    {
                        type: "expert",
                        id: "id",
                        name: "name",
                        description: "description",
                        systemPrompt: "systemPrompt",
                    },
                ],
            },
        ];
        server.mockEndpoint().get("/agents").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.agents.list();
        expect(response).toEqual([
            {
                id: "id",
                name: "name",
                description: "description",
                systemPrompt: "systemPrompt",
                experts: [
                    {
                        type: "expert",
                        id: "id",
                        name: "name",
                        description: "description",
                        systemPrompt: "systemPrompt",
                    },
                ],
            },
        ]);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CortiClient({
            maxRetries: 0,
            token: "test",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/agents").respondWith().statusCode(400).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agents.list();
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CortiClient({
            maxRetries: 0,
            token: "test",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };
        server.mockEndpoint().get("/agents").respondWith().statusCode(401).jsonBody(rawResponseBody).build();

        await expect(async () => {
            return await client.agents.list();
        }).rejects.toThrow(Corti.UnauthorizedError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CortiClient({
            maxRetries: 0,
            token: "test",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { name: "name", description: "description" };
        const rawResponseBody = {
            id: "id",
            name: "name",
            description: "description",
            systemPrompt: "systemPrompt",
            experts: [
                {
                    type: "expert",
                    id: "id",
                    name: "name",
                    description: "description",
                    systemPrompt: "systemPrompt",
                    mcpServers: [
                        { id: "id", name: "name", transportType: "stdio", authorizationType: "none", url: "url" },
                    ],
                },
            ],
        };
        server
            .mockEndpoint()
            .post("/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agents.create({
            name: "name",
            description: "description",
        });
        expect(response).toEqual({
            id: "id",
            name: "name",
            description: "description",
            systemPrompt: "systemPrompt",
            experts: [
                {
                    type: "expert",
                    id: "id",
                    name: "name",
                    description: "description",
                    systemPrompt: "systemPrompt",
                    mcpServers: [
                        {
                            id: "id",
                            name: "name",
                            transportType: "stdio",
                            authorizationType: "none",
                            url: "url",
                        },
                    ],
                },
            ],
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CortiClient({
            maxRetries: 0,
            token: "test",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { name: "name", description: "description" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.create({
                name: "name",
                description: "description",
            });
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CortiClient({
            maxRetries: 0,
            token: "test",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = { name: "name", description: "description" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/agents")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.agents.create({
                name: "name",
                description: "description",
            });
        }).rejects.toThrow(Corti.UnauthorizedError);
    });
});
