// This file was auto-generated by Fern from our API Definition.

import * as Corti from "../../src/api/index";
import { CortiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";
import { mockOAuth } from "./mockAuth";

describe("AlphaSectionVersionsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = [
            {
                id: "id",
                versionNumber: 1,
                generation: {
                    heading: "heading",
                    instructions: { contentPrompt: "contentPrompt" },
                    outputSchema: { type: "string" },
                },
            },
        ];

        server
            .mockEndpoint()
            .get("/alpha/sections/sectionID/versions/")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.alphaSectionVersions.list("sectionID");
        expect(response).toEqual([
            {
                id: "id",
                versionNumber: 1,
                generation: {
                    heading: "heading",
                    instructions: {
                        contentPrompt: "contentPrompt",
                    },
                    outputSchema: {
                        type: "string",
                    },
                },
            },
        ]);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/alpha/sections/sectionID/versions/")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.alphaSectionVersions.list("sectionID");
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            generation: {
                heading: "heading",
                instructions: { contentPrompt: "contentPrompt" },
                outputSchema: { type: "string" },
            },
        };
        const rawResponseBody = {
            id: "id",
            versionNumber: 1,
            generation: {
                heading: "heading",
                instructions: {
                    contentPrompt: "contentPrompt",
                    writingStylePrompt: "writingStylePrompt",
                    miscPrompt: "miscPrompt",
                },
                outputSchema: {
                    type: "string",
                    description: "description",
                    default: "default",
                    enum: ["enum"],
                    pattern: "pattern",
                },
            },
        };

        server
            .mockEndpoint()
            .post("/alpha/sections/sectionID/versions/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.alphaSectionVersions.create("sectionID", {
            generation: {
                heading: "heading",
                instructions: {
                    contentPrompt: "contentPrompt",
                },
                outputSchema: {
                    type: "string",
                },
            },
        });
        expect(response).toEqual({
            id: "id",
            versionNumber: 1,
            generation: {
                heading: "heading",
                instructions: {
                    contentPrompt: "contentPrompt",
                    writingStylePrompt: "writingStylePrompt",
                    miscPrompt: "miscPrompt",
                },
                outputSchema: {
                    type: "string",
                    description: "description",
                    default: "default",
                    enum: ["enum"],
                    pattern: "pattern",
                },
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            generation: {
                heading: "heading",
                instructions: { contentPrompt: "contentPrompt" },
                outputSchema: { type: "string" },
            },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/alpha/sections/sectionID/versions/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.alphaSectionVersions.create("sectionID", {
                generation: {
                    heading: "heading",
                    instructions: {
                        contentPrompt: "contentPrompt",
                    },
                    outputSchema: {
                        type: "string",
                    },
                },
            });
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            generation: {
                heading: "heading",
                instructions: { contentPrompt: "contentPrompt" },
                outputSchema: { type: "string" },
            },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/alpha/sections/sectionID/versions/")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.alphaSectionVersions.create("sectionID", {
                generation: {
                    heading: "heading",
                    instructions: {
                        contentPrompt: "contentPrompt",
                    },
                    outputSchema: {
                        type: "string",
                    },
                },
            });
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = {
            id: "id",
            versionNumber: 1,
            generation: {
                heading: "heading",
                instructions: {
                    contentPrompt: "contentPrompt",
                    writingStylePrompt: "writingStylePrompt",
                    miscPrompt: "miscPrompt",
                },
                outputSchema: {
                    type: "string",
                    description: "description",
                    default: "default",
                    enum: ["enum"],
                    pattern: "pattern",
                },
            },
        };

        server
            .mockEndpoint()
            .get("/alpha/sections/sectionID/versions/versionID")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.alphaSectionVersions.get("sectionID", "versionID");
        expect(response).toEqual({
            id: "id",
            versionNumber: 1,
            generation: {
                heading: "heading",
                instructions: {
                    contentPrompt: "contentPrompt",
                    writingStylePrompt: "writingStylePrompt",
                    miscPrompt: "miscPrompt",
                },
                outputSchema: {
                    type: "string",
                    description: "description",
                    default: "default",
                    enum: ["enum"],
                    pattern: "pattern",
                },
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/alpha/sections/sectionID/versions/versionID")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.alphaSectionVersions.get("sectionID", "versionID");
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        server
            .mockEndpoint()
            .delete("/alpha/sections/sectionID/versions/versionID")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.alphaSectionVersions.delete("sectionID", "versionID");
        expect(response).toEqual(undefined);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/alpha/sections/sectionID/versions/versionID")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.alphaSectionVersions.delete("sectionID", "versionID");
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("publish (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = {
            status: "status",
            evidence: { evidenceId: "f47ac10b-58cc-4372-a567-0e02b2c3d479", type: "transcript", quote: "quote" },
        };

        server
            .mockEndpoint()
            .post("/alpha/sections/sectionID/versions/versionID/publish")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.alphaSectionVersions.publish("sectionID", "versionID");
        expect(response).toEqual({
            status: "status",
            evidence: {
                evidenceId: "f47ac10b-58cc-4372-a567-0e02b2c3d479",
                type: "transcript",
                quote: "quote",
            },
        });
    });

    test("publish (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/alpha/sections/sectionID/versions/versionID/publish")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.alphaSectionVersions.publish("sectionID", "versionID");
        }).rejects.toThrow(Corti.NotFoundError);
    });
});
