// This file was auto-generated by Fern from our API Definition.

import * as Corti from "../../src/api/index";
import { CortiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";

describe("AuthClient", () => {
    test("token (1)", async () => {
        const server = mockServerPool.createServer();
        const client = new CortiClient({
            maxRetries: 0,
            tenantName: "base",
            token: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            client_id: "client_id",
            client_secret: "client_secret",
            grant_type: "client_credentials",
        };
        const rawResponseBody = { access_token: "access_token", expires_in: 1, token_type: "Bearer", scope: "scope" };
        server
            .mockEndpoint()
            .post("/base/protocol/openid-connect/token")
            .formUrlEncodedBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.auth.token({
            clientId: "client_id",
            clientSecret: "client_secret",
            grantType: "client_credentials",
        });
        expect(response).toEqual({
            accessToken: "access_token",
            expiresIn: 1,
            tokenType: "Bearer",
            scope: "scope",
        });
    });

    test("token (2)", async () => {
        const server = mockServerPool.createServer();
        const client = new CortiClient({
            maxRetries: 0,
            tenantName: "tenantName",
            token: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            client_id: "client_id",
            client_secret: "client_secret",
            grant_type: "client_credentials",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/tenantName/protocol/openid-connect/token")
            .formUrlEncodedBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.auth.token({
                clientId: "client_id",
                clientSecret: "client_secret",
                grantType: "client_credentials",
            });
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("token (3)", async () => {
        const server = mockServerPool.createServer();
        const client = new CortiClient({
            maxRetries: 0,
            tenantName: "tenantName",
            token: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            client_id: "client_id",
            client_secret: "client_secret",
            grant_type: "client_credentials",
        };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/tenantName/protocol/openid-connect/token")
            .formUrlEncodedBody(rawRequestBody)
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.auth.token({
                clientId: "client_id",
                clientSecret: "client_secret",
                grantType: "client_credentials",
            });
        }).rejects.toThrow(Corti.UnauthorizedError);
    });
});
