// This file was auto-generated by Fern from our API Definition.

import * as Corti from "../../src/api/index";
import { CortiClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";
import { mockOAuth } from "./mockAuth";

describe("SectionVersionsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = [
            {
                id: "id",
                versionNumber: 1,
                title: "title",
                instructions: { contentPrompt: "contentPrompt", writingStylePrompt: "writingStylePrompt" },
                outputSchema: {
                    type: "string",
                    description: "description",
                    default: "default",
                    enum: ["enum"],
                    pattern: "pattern",
                },
            },
        ];

        server
            .mockEndpoint()
            .get("/new/sections/sectionID/versions")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sectionVersions.list("sectionID");
        expect(response).toEqual([
            {
                id: "id",
                versionNumber: 1,
                title: "title",
                instructions: {
                    contentPrompt: "contentPrompt",
                    writingStylePrompt: "writingStylePrompt",
                },
                outputSchema: {
                    type: "string",
                    description: "description",
                    default: "default",
                    enum: ["enum"],
                    pattern: "pattern",
                },
            },
        ]);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/new/sections/sectionID/versions")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sectionVersions.list("sectionID");
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            title: "title",
            instructions: { contentPrompt: "contentPrompt", writingStylePrompt: "writingStylePrompt" },
        };
        const rawResponseBody = {
            id: "id",
            versionNumber: 1,
            title: "title",
            instructions: { contentPrompt: "contentPrompt", writingStylePrompt: "writingStylePrompt" },
            outputSchema: {
                type: "string",
                description: "description",
                default: "default",
                enum: ["enum"],
                pattern: "pattern",
            },
        };

        server
            .mockEndpoint()
            .post("/new/sections/sectionID/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sectionVersions.create("sectionID", {
            title: "title",
            instructions: {
                contentPrompt: "contentPrompt",
                writingStylePrompt: "writingStylePrompt",
            },
        });
        expect(response).toEqual({
            id: "id",
            versionNumber: 1,
            title: "title",
            instructions: {
                contentPrompt: "contentPrompt",
                writingStylePrompt: "writingStylePrompt",
            },
            outputSchema: {
                type: "string",
                description: "description",
                default: "default",
                enum: ["enum"],
                pattern: "pattern",
            },
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            title: "title",
            instructions: { contentPrompt: "contentPrompt", writingStylePrompt: "writingStylePrompt" },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/new/sections/sectionID/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sectionVersions.create("sectionID", {
                title: "title",
                instructions: {
                    contentPrompt: "contentPrompt",
                    writingStylePrompt: "writingStylePrompt",
                },
            });
        }).rejects.toThrow(Corti.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });
        const rawRequestBody = {
            title: "title",
            instructions: { contentPrompt: "contentPrompt", writingStylePrompt: "writingStylePrompt" },
        };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/new/sections/sectionID/versions")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sectionVersions.create("sectionID", {
                title: "title",
                instructions: {
                    contentPrompt: "contentPrompt",
                    writingStylePrompt: "writingStylePrompt",
                },
            });
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("get (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = {
            id: "id",
            versionNumber: 1,
            title: "title",
            instructions: { contentPrompt: "contentPrompt", writingStylePrompt: "writingStylePrompt" },
            outputSchema: {
                type: "string",
                description: "description",
                default: "default",
                enum: ["enum"],
                pattern: "pattern",
            },
        };

        server
            .mockEndpoint()
            .get("/new/sections/sectionID/versions/versionID")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sectionVersions.get("sectionID", "versionID");
        expect(response).toEqual({
            id: "id",
            versionNumber: 1,
            title: "title",
            instructions: {
                contentPrompt: "contentPrompt",
                writingStylePrompt: "writingStylePrompt",
            },
            outputSchema: {
                type: "string",
                description: "description",
                default: "default",
                enum: ["enum"],
                pattern: "pattern",
            },
        });
    });

    test("get (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/new/sections/sectionID/versions/versionID")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sectionVersions.get("sectionID", "versionID");
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        server
            .mockEndpoint()
            .delete("/new/sections/sectionID/versions/versionID")
            .respondWith()
            .statusCode(200)
            .build();

        const response = await client.sectionVersions.delete("sectionID", "versionID");
        expect(response).toEqual(undefined);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/new/sections/sectionID/versions/versionID")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sectionVersions.delete("sectionID", "versionID");
        }).rejects.toThrow(Corti.NotFoundError);
    });

    test("publish (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { status: "published" };

        server
            .mockEndpoint()
            .post("/new/sections/sectionID/versions/versionID/publish")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.sectionVersions.publish("sectionID", "versionID");
        expect(response).toEqual({
            status: "published",
        });
    });

    test("publish (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new CortiClient({
            maxRetries: 0,
            clientId: "client_id",
            clientSecret: "client_secret",
            tenantName: "test",
            environment: { base: server.baseUrl, wss: server.baseUrl, login: server.baseUrl, agents: server.baseUrl },
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/new/sections/sectionID/versions/versionID/publish")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.sectionVersions.publish("sectionID", "versionID");
        }).rejects.toThrow(Corti.NotFoundError);
    });
});
