// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../../../../api/index.js";
import * as core from "../../../../../../../core/index.js";
import type * as serializers from "../../../../../../index.js";
import { AgenticLabels } from "../../../../../../types/AgenticLabels.js";
import { AgenticLifecycle } from "../../../../../../types/AgenticLifecycle.js";
import { AgenticVisibility } from "../../../../../../types/AgenticVisibility.js";
import { CommonConnectorCreateRequest } from "../../../../../../types/CommonConnectorCreateRequest.js";

export const AgenticCreateRequest: core.serialization.Schema<
    serializers.agentic.AgenticCreateRequest.Raw,
    Corti.agentic.AgenticCreateRequest
> = core.serialization.object({
    name: core.serialization.string(),
    description: core.serialization.string().optional(),
    systemPrompt: core.serialization.string().optional(),
    model: core.serialization.string().optional(),
    visibility: AgenticVisibility.optional(),
    lifecycle: AgenticLifecycle.optional(),
    connectors: core.serialization.list(CommonConnectorCreateRequest).optional(),
    labels: AgenticLabels.optional(),
});

export declare namespace AgenticCreateRequest {
    export interface Raw {
        name: string;
        description?: string | null;
        systemPrompt?: string | null;
        model?: string | null;
        visibility?: AgenticVisibility.Raw | null;
        lifecycle?: AgenticLifecycle.Raw | null;
        connectors?: CommonConnectorCreateRequest.Raw[] | null;
        labels?: AgenticLabels.Raw | null;
    }
}
