// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";
import { GuidedDocument } from "../../../types/GuidedDocument.js";

export const Response: core.serialization.Schema<serializers.documents.list.Response.Raw, Corti.GuidedDocument[]> =
    core.serialization.list(GuidedDocument);

export declare namespace Response {
    export type Raw = GuidedDocument.Raw[];
}
