// This file was auto-generated by Fern from our API Definition.

import { AuthClient } from "./api/resources/auth/client/Client.js";
import { InteractionsClient } from "./api/resources/interactions/client/Client.js";
import { OauthClient } from "./api/resources/oauth/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace CortiClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class CortiClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<CortiClient.Options>;
    protected _interactions: InteractionsClient | undefined;
    protected _auth: AuthClient | undefined;
    protected _oauth: OauthClient | undefined;

    constructor(options: CortiClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get interactions(): InteractionsClient {
        return (this._interactions ??= new InteractionsClient(this._options));
    }

    public get auth(): AuthClient {
        return (this._auth ??= new AuthClient(this._options));
    }

    public get oauth(): OauthClient {
        return (this._oauth ??= new OauthClient(this._options));
    }
}
