// This file was auto-generated by Fern from our API Definition.

export interface CortiEnvironmentUrls {
    base: string;
    wss: string;
    login: string;
    agents: string;
}

export const CortiEnvironment = {
    Eu: {
        base: "https://api.eu.corti.app/v2",
        wss: "wss://api.eu.corti.app/audio-bridge/v2",
        login: "https://auth.eu.corti.app/realms",
        agents: "https://api.eu.corti.app",
    },
    Us: {
        base: "https://api.us.corti.app/v2",
        wss: "wss://api.us.corti.app/audio-bridge/v2",
        login: "https://auth.us.corti.app/realms",
        agents: "https://api.us.corti.app",
    },
} as const;

export type CortiEnvironment = typeof CortiEnvironment.Eu | typeof CortiEnvironment.Us;
