/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../index.js";
import * as Corti from "../../../../api/index.js";
import * as core from "../../../../core/index.js";

export const FactsGenerateRequestContextItem: core.serialization.ObjectSchema<
    serializers.FactsGenerateRequestContextItem.Raw,
    Corti.FactsGenerateRequestContextItem
> = core.serialization.object({
    data: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
    type: core.serialization.stringLiteral("string"),
});

export declare namespace FactsGenerateRequestContextItem {
    export interface Raw {
        data: Record<string, unknown>;
        type: "string";
    }
}
