// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface LanguagesListRequest {
    /** Field used to filter languages that supported specific endpoint. */
    endpoint?: Corti.LanguagesListRequestEndpoint;
}
