/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Corti from "../../../../index.js";

/**
 * @example
 *     {
 *         body: {
 *             context: [{
 *                     type: "facts",
 *                     data: [{
 *                             text: "text",
 *                             source: "core"
 *                         }]
 *                 }],
 *             templateKey: "templateKey",
 *             outputLanguage: "outputLanguage"
 *         }
 *     }
 */
export interface DocumentsCreateRequest {
    /**
     * With the optional header `X-Corti-Retention-Policy:none` the API will generate and return the document as expected, but the generated document will not be saved to the database. The response will include the header `X-Corti-Retention-Policy:acknowledged` to confirm that your retention preference was respected. If the header is omitted or set to any other value, the default retention policy will apply, and the document will be stored in the database.
     */
    cortiRetentionPolicy?: "none" | null;
    body: Corti.DocumentsCreateBodyRequest;
}
