// This file was auto-generated by Fern from our API Definition.

import type * as Corti from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface CreateTemplateVersionRequest {
    instructions?: Corti.TemplateInstructions;
    sections?: Corti.TemplateVersionSectionRequest[];
}
